# Generated by Django 5.0.2 on 2026-05-19 20:38

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0018_remove_rolepermission_permission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="محفوظ حتى لو حُذف المستخدم",
                        max_length=150,
                        verbose_name="اسم المستخدم",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="مثل: CREATE, UPDATE, DELETE, LOGIN, APPROVE, REJECT, EXPORT",
                        max_length=50,
                        verbose_name="العملية",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="اسم النموذج"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="معرف الكائن"),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="البيانات القديمة"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="البيانات الجديدة"
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="المستند أو المذكرة المبررة — إجباري للعمليات الحساسة",
                        verbose_name="سبب التغيير",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="معرف الجلسة"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "معلومات"),
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالي"),
                            ("critical", "حرج"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="مستوى الحساسية",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثل: personnel, services, security, system",
                        max_length=50,
                        verbose_name="النظام الفرعي",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="التوقيت"
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 — لمنع التلاعب",
                        max_length=64,
                        verbose_name="التوقيع الرقمي",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="يُؤرشف بعد 5 سنوات — يُحتفظ به 10 سنوات",
                        verbose_name="مؤرشف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(fields=["action"], name="audit_log_action_b32d4d_idx"),
                    models.Index(
                        fields=["model_name"], name="audit_log_model_n_d0c22c_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_log_user_id_835db7_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_log_timesta_e8e14e_idx"
                    ),
                    models.Index(
                        fields=["module", "action"], name="audit_log_module_2b88a0_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="audit_log_severit_33a46a_idx"
                    ),
                    models.Index(
                        fields=["is_archived", "timestamp"],
                        name="audit_log_is_arch_551d30_idx",
                    ),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["timestamp"], name="audit_log_timestamp_brin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_attempted",
                    models.CharField(
                        max_length=150, verbose_name="اسم المستخدم المُدخل"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "دخول ناجح"),
                            ("LOGIN_FAILED", "دخول فاشل"),
                            ("LOGOUT", "خروج"),
                            ("TOKEN_REFRESH", "تجديد توكن"),
                            ("ACCOUNT_LOCKED", "قفل حساب"),
                            ("ACCOUNT_UNLOCKED", "فتح حساب"),
                            ("PASSWORD_CHANGED", "تغيير كلمة مرور"),
                            ("PASSWORD_RESET", "إعادة تعيين كلمة مرور"),
                            ("SESSION_REVOKED", "إلغاء جلسة"),
                            ("SUSPICIOUS_LOGIN", "دخول مشبوه"),
                        ],
                        max_length=20,
                        verbose_name="الحدث",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "لا يوجد"),
                            ("invalid_password", "كلمة مرور خاطئة"),
                            ("account_locked", "حساب مغلق"),
                            ("account_disabled", "حساب معطل"),
                            ("user_not_found", "مستخدم غير موجود"),
                            ("two_factor_failed", "فشل التحقق الثنائي"),
                            ("session_expired", "جلسة منتهية"),
                            ("token_invalid", "توكن غير صالح"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="سبب الفشل",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="معرف الجلسة"
                    ),
                ),
                (
                    "geo_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="يُحسب من IP إذا متاح",
                        max_length=100,
                        verbose_name="الموقع الجغرافي",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل دخول",
                "verbose_name_plural": "سجلات الدخول",
                "db_table": "audit_login_log",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_login_action_df7040_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_login_user_id_e99063_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_login_ip_addr_92bd10_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_login_timesta_625911_idx"
                    ),
                    models.Index(
                        fields=["username_attempted"],
                        name="audit_login_usernam_e91293_idx",
                    ),
                    models.Index(
                        fields=["failure_reason"], name="audit_login_failure_35239f_idx"
                    ),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["timestamp"], name="login_audit_timestamp_brin"
                    ),
                ],
            },
        ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_audit_log RENAME TO audit_log;",
                    reverse_sql="ALTER TABLE IF EXISTS audit_log RENAME TO core_audit_log;"
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS username VARCHAR(150) DEFAULT '' NOT NULL;
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS change_reason TEXT DEFAULT '' NOT NULL;
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS session_key VARCHAR(64) NULL;
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS severity VARCHAR(10) DEFAULT 'info' NOT NULL;
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS module VARCHAR(50) DEFAULT '' NOT NULL;
                    ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT FALSE NOT NULL;

                    CREATE INDEX IF NOT EXISTS audit_log_action_b32d4d_idx ON audit_log (action);
                    CREATE INDEX IF NOT EXISTS audit_log_model_n_d0c22c_idx ON audit_log (model_name);
                    CREATE INDEX IF NOT EXISTS audit_log_user_id_835db7_idx ON audit_log (user_id, timestamp);
                    CREATE INDEX IF NOT EXISTS audit_log_timesta_e8e14e_idx ON audit_log (timestamp);
                    CREATE INDEX IF NOT EXISTS audit_log_module_2b88a0_idx ON audit_log (module, action);
                    CREATE INDEX IF NOT EXISTS audit_log_severit_33a46a_idx ON audit_log (severity);
                    CREATE INDEX IF NOT EXISTS audit_log_is_arch_551d30_idx ON audit_log (is_archived, timestamp);
                    CREATE INDEX IF NOT EXISTS audit_log_timestamp_brin ON audit_log USING BRIN (timestamp);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS audit_log_action_b32d4d_idx;
                    DROP INDEX IF EXISTS audit_log_model_n_d0c22c_idx;
                    DROP INDEX IF EXISTS audit_log_user_id_835db7_idx;
                    DROP INDEX IF EXISTS audit_log_timesta_e8e14e_idx;
                    DROP INDEX IF EXISTS audit_log_module_2b88a0_idx;
                    DROP INDEX IF EXISTS audit_log_severit_33a46a_idx;
                    DROP INDEX IF EXISTS audit_log_is_arch_551d30_idx;
                    DROP INDEX IF EXISTS audit_log_timestamp_brin;

                    ALTER TABLE audit_log DROP COLUMN IF EXISTS username;
                    ALTER TABLE audit_log DROP COLUMN IF EXISTS change_reason;
                    ALTER TABLE audit_log DROP COLUMN IF EXISTS session_key;
                    ALTER TABLE audit_log DROP COLUMN IF EXISTS severity;
                    ALTER TABLE audit_log DROP COLUMN IF EXISTS module;
                    ALTER TABLE audit_log DROP COLUMN IF EXISTS is_archived;
                    """
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_login_audit_log RENAME TO audit_login_log;",
                    reverse_sql="ALTER TABLE IF EXISTS audit_login_log RENAME TO core_login_audit_log;"
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE audit_login_log ADD COLUMN IF NOT EXISTS session_key VARCHAR(64) NULL;
                    ALTER TABLE audit_login_log ADD COLUMN IF NOT EXISTS geo_location VARCHAR(100) DEFAULT '' NOT NULL;

                    CREATE INDEX IF NOT EXISTS audit_login_action_df7040_idx ON audit_login_log (action, timestamp);
                    CREATE INDEX IF NOT EXISTS audit_login_user_id_e99063_idx ON audit_login_log (user_id, timestamp);
                    CREATE INDEX IF NOT EXISTS audit_login_ip_addr_92bd10_idx ON audit_login_log (ip_address);
                    CREATE INDEX IF NOT EXISTS audit_login_timesta_625911_idx ON audit_login_log (timestamp);
                    CREATE INDEX IF NOT EXISTS audit_login_usernam_e91293_idx ON audit_login_log (username_attempted);
                    CREATE INDEX IF NOT EXISTS audit_login_failure_35239f_idx ON audit_login_log (failure_reason);
                    CREATE INDEX IF NOT EXISTS login_audit_timestamp_brin ON audit_login_log USING BRIN (timestamp);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS audit_login_action_df7040_idx;
                    DROP INDEX IF EXISTS audit_login_user_id_e99063_idx;
                    DROP INDEX IF EXISTS audit_login_ip_addr_92bd10_idx;
                    DROP INDEX IF EXISTS audit_login_timesta_625911_idx;
                    DROP INDEX IF EXISTS audit_login_usernam_e91293_idx;
                    DROP INDEX IF EXISTS audit_login_failure_35239f_idx;
                    DROP INDEX IF EXISTS login_audit_timestamp_brin;

                    ALTER TABLE audit_login_log DROP COLUMN IF EXISTS session_key;
                    ALTER TABLE audit_login_log DROP COLUMN IF EXISTS geo_location;
                    """
                ),
            ]
        )
    ]
