# Generated by Django 5.0.2 on 2026-04-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="الملف"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="Hash"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="الإصدار")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق",
                "verbose_name_plural": "المرفقات",
                "db_table": "services_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "service_month",
                    models.CharField(
                        max_length=7, unique=True, verbose_name="شهر الخدمة"
                    ),
                ),
                ("data", models.JSONField(verbose_name="البيانات")),
                ("locked", models.BooleanField(default=False, verbose_name="مقفل")),
            ],
            options={
                "verbose_name": "لقطة شهرية",
                "verbose_name_plural": "اللقطات الشهرية",
                "db_table": "services_monthly_snapshot",
                "ordering": ["-service_month"],
                "indexes": [
                    models.Index(
                        fields=["service_month"], name="services_mo_service_c59515_idx"
                    ),
                    models.Index(
                        fields=["locked"], name="services_mo_locked_d926a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StagingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("proposed_change", models.JSONField(verbose_name="التغيير المقترح")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "موافق عليه"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_records",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staging_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل مؤقت",
                "verbose_name_plural": "السجلات المؤقتة",
                "db_table": "services_staging_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تحديث"),
                            ("DELETE", "حذف"),
                            ("VIEW", "عرض"),
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                        ],
                        max_length=10,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="اسم النموذج"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="معرف الكائن"),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="البيانات القديمة"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="البيانات الجديدة"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, verbose_name="عنوان IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "db_table": "services_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="services_au_timesta_ac5ad1_idx"
                    ),
                    models.Index(
                        fields=["user", "action"], name="services_au_user_id_59822e_idx"
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="services_au_model_n_03220e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المهمة")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("attendance", "مطابقة حضور"),
                            ("payroll", "مطابقة راتب"),
                            ("qualification", "مطابقة مؤهلات"),
                        ],
                        max_length=20,
                        verbose_name="نوع المطابقة",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="reconciliation/%Y/%m/", verbose_name="ملف المصدر"
                    ),
                ),
                (
                    "key_field",
                    models.CharField(max_length=50, verbose_name="حقل الربط"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="النتيجة"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة مطابقة",
                "verbose_name_plural": "مهام المطابقة",
                "db_table": "services_reconciliation_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="services_re_status_895bcc_idx"
                    ),
                    models.Index(
                        fields=["task_type"], name="services_re_task_ty_bbb622_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("event_date", models.DateField(verbose_name="تاريخ الحدث")),
                (
                    "service_month",
                    models.CharField(max_length=7, verbose_name="شهر الخدمة"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="اسم الحقل"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="القيمة القديمة"),
                ),
                ("new_value", models.TextField(verbose_name="القيمة الجديدة")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "order_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="services.document",
                        verbose_name="المستند",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث",
                "verbose_name_plural": "الأحداث",
                "db_table": "services_event_log",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["personnel", "service_month"],
                        name="services_ev_personn_4d5b3a_idx",
                    ),
                    models.Index(
                        fields=["service_month", "field_name"],
                        name="services_ev_service_834be1_idx",
                    ),
                    models.Index(
                        fields=["event_date"], name="services_ev_event_d_63436d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="serviceeventlog",
            constraint=models.UniqueConstraint(
                fields=("personnel", "service_month", "field_name"),
                name="unique_event_per_month",
            ),
        ),
        migrations.AddIndex(
            model_name="stagingrecord",
            index=models.Index(fields=["status"], name="services_st_status_b1bafd_idx"),
        ),
        migrations.AddIndex(
            model_name="stagingrecord",
            index=models.Index(
                fields=["personnel", "status"], name="services_st_personn_5b29e5_idx"
            ),
        ),
    ]
