# Generated by Django 5.0.2 on 2026-04-02 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_add_phase2_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="departmentcompliance",
            new_name="services_de_service_fd876d_idx",
            old_name="services_de_service_idx",
        ),
        migrations.RenameIndex(
            model_name="departmentcompliance",
            new_name="services_de_quality_5f2e46_idx",
            old_name="services_de_quality_idx",
        ),
        migrations.RenameIndex(
            model_name="exportlog",
            new_name="services_ex_export__1e0e61_idx",
            old_name="services_ex_export__idx",
        ),
        migrations.RenameIndex(
            model_name="exportlog",
            new_name="services_ex_departm_400472_idx",
            old_name="services_ex_departm_idx",
        ),
        migrations.RenameIndex(
            model_name="exportlog",
            new_name="services_ex_status_2bd86c_idx",
            old_name="services_ex_status_idx",
        ),
        migrations.RenameIndex(
            model_name="rejectionlog",
            new_name="services_re_departm_115ce8_idx",
            old_name="services_re_departm_idx",
        ),
        migrations.RenameIndex(
            model_name="rejectionlog",
            new_name="services_re_rejecte_6bd373_idx",
            old_name="services_re_rejecte_idx",
        ),
        migrations.RenameIndex(
            model_name="stagingrecord",
            new_name="services_st_upload__e6ddd4_idx",
            old_name="services_st_upload__idx",
        ),
        migrations.RenameIndex(
            model_name="stagingrecord",
            new_name="services_st_severit_6f2dd9_idx",
            old_name="services_st_severit_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="signature",
            field=models.CharField(
                blank=True,
                help_text="HMAC-SHA256 لمنع التلاعب",
                max_length=64,
                verbose_name="التوقيع الرقمي",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("temp", "مؤقت"),
                    ("committed", "مثبت"),
                    ("archived", "مؤرشف"),
                ],
                default="committed",
                max_length=20,
                verbose_name="حالة الملف",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="temp_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تنتهي صلاحية المؤقت في"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="temp_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مالك الملف المؤقت",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "إنشاء"),
                    ("UPDATE", "تحديث"),
                    ("DELETE", "حذف"),
                    ("VIEW", "عرض"),
                    ("LOGIN", "تسجيل دخول"),
                    ("LOGOUT", "تسجيل خروج"),
                    ("LOGIN_FAILED", "محاولة دخول فاشلة"),
                    ("EXPORT", "تصدير"),
                    ("IMPORT", "استيراد"),
                    ("APPROVE", "اعتماد"),
                    ("REJECT", "رفض"),
                ],
                max_length=20,
                verbose_name="الإجراء",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="services_au_action_b8ee6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="services_do_status_af5c5b_idx"),
        ),
    ]
