# Generated by Django 5.0.2 on 2026-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_phase4_webhook_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(verbose_name="التوقيت"),
        ),
    ]
