# Generated by Django 5.0.2 on 2026-04-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_directorate_governorate_division_and_more"),
        ("services", "0006_auditlog_governorate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentcompliance",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_records",
                to="core.directorate",
                verbose_name="الإدارة العامة / المديرية",
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="export_logs",
                to="core.directorate",
                verbose_name="الإدارة العامة / المديرية",
            ),
        ),
        migrations.AddField(
            model_name="monthlysnapshot",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_snapshots",
                to="core.directorate",
                verbose_name="الإدارة العامة / المديرية",
            ),
        ),
        migrations.AddField(
            model_name="rejectionlog",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejections",
                to="core.directorate",
                verbose_name="الإدارة العامة / المديرية",
            ),
        ),
        migrations.AddField(
            model_name="webhookconfig",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_configs",
                to="core.directorate",
                verbose_name="الإدارة العامة / المديرية",
            ),
        ),
        migrations.AlterField(
            model_name="departmentcompliance",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_records",
                to="core.department",
                verbose_name="الإدارة (القديمة)",
            ),
        ),
        migrations.AlterField(
            model_name="exportlog",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="export_logs",
                to="core.department",
                verbose_name="الإدارة (القديمة)",
            ),
        ),
        migrations.AlterField(
            model_name="rejectionlog",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejections",
                to="core.department",
                verbose_name="الإدارة (القديمة)",
            ),
        ),
        migrations.AlterField(
            model_name="webhookconfig",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="فارغ = جميع الإدارات",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_configs",
                to="core.department",
                verbose_name="الإدارة (القديمة)",
            ),
        ),
    ]
