# Generated by Django 5.0.2 on 2026-05-02 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_statetransitionrule_and_more"),
        ("personnel", "0007_personnelmaster_category_and_more"),
        ("services", "0007_departmentcompliance_directorate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("late_submission", "تأخر في تسليم الكشوفات"),
                            ("retirement_alert", "اقتراب سن التقاعد"),
                            ("correction_pending", "طلب تصحيح معلق"),
                            ("secondment_expiring", "انتهاء فترة انتداب"),
                            ("study_ending", "انتهاء فترة دراسة"),
                            ("sentence_ending", "انتهاء مدة حكم"),
                            ("dual_auth_pending", "طلب تفويض مزدوج معلق"),
                            ("month_closing", "اقتراب موعد إقفال الشهر"),
                            ("status_change_approved", "تم اعتماد تغيير الحالة"),
                            ("status_change_rejected", "تم رفض تغيير الحالة"),
                        ],
                        max_length=30,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالي"),
                            ("critical", "حرج"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="الصفحة التي يتم توجيه المستخدم إليها",
                        max_length=500,
                        verbose_name="رابط الإجراء",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تم القراءة"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه",
                "verbose_name_plural": "التنبيهات",
                "db_table": "services_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusChangeForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("retirement_age", "بلوغ السن القانوني"),
                            ("death", "وفاة"),
                            ("missing", "مفقود"),
                            ("medical_unfit", "عدم لياقة صحية"),
                            ("end_of_service", "إنهاء مدة"),
                            ("retired", "محال للتقاعد"),
                            ("imprisoned", "مسجون"),
                            ("escort", "مرافق / معيات"),
                            ("martyr", "شهيد"),
                            ("study_leave", "مفرغ للدراسة"),
                            ("seconded", "منتدب"),
                        ],
                        max_length=30,
                        verbose_name="نوع الاستمارة",
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        default=dict,
                        help_text="البيانات التفصيلية حسب نوع الاستمارة",
                        verbose_name="بيانات الاستمارة",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النفاذ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_services", "بانتظار قسم الخدمات"),
                            ("pending_hr", "بانتظار مدير الموارد البشرية"),
                            ("pending_director", "بانتظار المدير العام"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="حالة الاستمارة",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التقديم"
                    ),
                ),
                ("services_approved_at", models.DateTimeField(blank=True, null=True)),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("director_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "required_attachments",
                    models.JSONField(
                        default=list,
                        help_text="قائمة أنواع المرفقات الإلزامية",
                        verbose_name="المرفقات المطلوبة",
                    ),
                ),
                (
                    "attachments_complete",
                    models.BooleanField(default=False, verbose_name="المرفقات مكتملة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "استمارة إثبات حالة",
                "verbose_name_plural": "استمارات إثبات الحالة",
                "db_table": "services_status_change_form",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="serviceeventlog",
            name="unique_event_per_month",
        ),
        migrations.AlterField(
            model_name="monthlysnapshot",
            name="service_month",
            field=models.CharField(max_length=7, verbose_name="شهر الخدمة"),
        ),
        migrations.AddConstraint(
            model_name="monthlysnapshot",
            constraint=models.UniqueConstraint(
                fields=("governorate", "directorate", "service_month"),
                name="unique_snapshot_per_org_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceeventlog",
            constraint=models.UniqueConstraint(
                fields=("personnel", "service_month", "field_name", "event_date"),
                name="unique_event_per_day",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecord",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="personnel.personnelmaster",
                verbose_name="الفرد المعني",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecord",
            name="target_directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.directorate",
                verbose_name="الإدارة المستهدفة",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecord",
            name="target_governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.governorate",
                verbose_name="المحافظة المستهدفة",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecord",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المستهدف",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="status_change_forms",
                to="services.document",
                verbose_name="المرفقات",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="director_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="director_approved_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتماد المدير العام",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="from_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forms_from",
                to="core.servicestatus",
                verbose_name="الحالة السابقة",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="governorate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_change_forms",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="hr_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_approved_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتماد الموارد البشرية",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="personnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_change_forms",
                to="personnel.personnelmaster",
                verbose_name="الفرد",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفض بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="services_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services_approved_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتماد قسم الخدمات",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مقدم الطلب",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="to_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forms_to",
                to="core.servicestatus",
                verbose_name="الحالة الجديدة",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["target_user", "is_read"], name="services_no_target__ef0374_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["notification_type"], name="services_no_notific_c60d51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["priority", "is_read"], name="services_no_priorit_5344a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["created_at"], name="services_no_created_dbd809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statuschangeform",
            index=models.Index(
                fields=["form_type", "status"], name="services_st_form_ty_017aac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statuschangeform",
            index=models.Index(
                fields=["personnel", "status"], name="services_st_personn_74014e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statuschangeform",
            index=models.Index(fields=["status"], name="services_st_status_6db128_idx"),
        ),
    ]
