# Generated by Django 5.0.2 on 2026-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_statetransitionrule_and_more"),
        ("services", "0008_notificationrecord_statuschangeform_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="departmentcompliance",
            constraint=models.UniqueConstraint(
                fields=("governorate", "directorate", "department", "service_month"),
                name="unique_compliance_per_org_month",
            ),
        ),
    ]
