# Generated by Django 5.0.2 on 2026-05-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0013_hardening_military_number_rank_settlement"),
        ("services", "0009_departmentcompliance_unique_compliance_per_org_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id_front", "بطاقة وطنية - أمامي"),
                    ("national_id_back", "بطاقة وطنية - خلفي"),
                    ("national_id_scan", "بطاقة وطنية - ماسح ضوئي"),
                    ("rank_decision", "قرار ترقية"),
                    ("settlement_decision", "قرار تسوية"),
                    ("other", "أخرى"),
                ],
                default="other",
                help_text="تصنيف المرفق — بطاقة وطنية، قرار ترقية، إلخ",
                max_length=30,
                verbose_name="نوع المرفق",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="personnel.personnelmaster",
                verbose_name="الفرد",
            ),
        ),
    ]
