# Generated by Django 5.0.2 on 2026-05-15 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_protect_document_personnel_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "form_type",
                    models.SlugField(
                        help_text="مثال: wounded, transferred — بالإنجليزية بدون مسافات",
                        unique=True,
                        verbose_name="معرّف الاستمارة",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="اسم الاستمارة"),
                ),
                (
                    "target_status",
                    models.CharField(
                        help_text="اسم الحالة الخدمية التي ينتقل إليها الفرد",
                        max_length=100,
                        verbose_name="الحالة المستهدفة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text='[{"key":"...", "label":"...", "type":"text|date|select|textarea", "required":true, "options":["أ","ب"]}]',
                        verbose_name="حقول بيانات الحالة",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        default=list,
                        help_text='[{"doc_type":"...", "label":"...", "required":true}]',
                        verbose_name="المرفقات المطلوبة",
                    ),
                ),
                (
                    "min_documents",
                    models.PositiveIntegerField(
                        default=1, verbose_name="أقل عدد مرفقات"
                    ),
                ),
                (
                    "max_documents",
                    models.PositiveIntegerField(
                        default=10, verbose_name="أقصى عدد مرفقات"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
            ],
            options={
                "verbose_name": "استمارة مخصصة",
                "verbose_name_plural": "الاستمارات المخصصة",
                "db_table": "services_custom_form_template",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="CustomReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "model_number",
                    models.PositiveIntegerField(
                        help_text="يبدأ من 26 — الأرقام 1-25 محجوزة",
                        unique=True,
                        verbose_name="رقم النموذج",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان النموذج"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("detail", "تفصيلي"),
                            ("aggregation", "خلاصة عددية"),
                            ("status_based", "حسب الحالة"),
                        ],
                        default="detail",
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="التصنيف")),
                (
                    "parent_section",
                    models.CharField(max_length=100, verbose_name="القسم الرئيسي"),
                ),
                (
                    "sub_section",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="القسم الفرعي"
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text='[{"key":"rank", "label":"الرتبة", "source":"personnel.current_rank.name"}]',
                        verbose_name="أعمدة الجدول",
                    ),
                ),
                (
                    "base_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"current_status__name": "..."} — فلتر ORM',
                        verbose_name="فلتر البيانات",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نموذج تقرير مخصص",
                "verbose_name_plural": "النماذج المخصصة",
                "db_table": "services_custom_report_template",
                "ordering": ["model_number"],
            },
        ),
    ]
