# Generated by Django 5.0.2 on 2026-05-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0015_alter_ranksettlement_supporting_document_and_more"),
        (
            "services",
            "0015_remove_document_personnel_remove_document_temp_owner_and_more",
        ),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceeventlog",
            name="order_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="storage.document",
                verbose_name="المستند",
            ),
        ),
        migrations.AlterField(
            model_name="statuschangeform",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="status_change_forms",
                to="storage.document",
                verbose_name="المرفقات",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Document",
                ),
            ],
            database_operations=[],
        ),
    ]
