# Generated by Django 5.0.2 on 2026-05-20 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_department_unique_together_and_more"),
        ("personnel", "0019_add_demotion_settlement_type"),
        ("services", "0016_alter_serviceeventlog_order_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentcompliance",
            options={
                "ordering": ["-service_month", "directorate"],
                "verbose_name": "التزام إدارة",
                "verbose_name_plural": "التزام الإدارات",
            },
        ),
        migrations.RemoveConstraint(
            model_name="departmentcompliance",
            name="unique_compliance_per_org_month",
        ),
        migrations.RemoveIndex(
            model_name="exportlog",
            name="services_ex_departm_400472_idx",
        ),
        migrations.RemoveIndex(
            model_name="rejectionlog",
            name="services_re_departm_115ce8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="departmentcompliance",
            unique_together={("directorate", "service_month")},
        ),
        migrations.RemoveField(
            model_name="exportlog",
            name="department",
        ),
        migrations.RemoveField(
            model_name="rejectionlog",
            name="department",
        ),
        migrations.RemoveField(
            model_name="webhookconfig",
            name="department",
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["directorate", "service_month"],
                name="services_ex_directo_c6ea33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionlog",
            index=models.Index(
                fields=["directorate", "service_month"],
                name="services_re_directo_3e2a3b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentcompliance",
            constraint=models.UniqueConstraint(
                fields=("governorate", "directorate", "service_month"),
                name="unique_compliance_per_org_month",
            ),
        ),
        migrations.RemoveField(
            model_name="departmentcompliance",
            name="department",
        ),
    ]
