# Generated by Django 5.0.2 on 2026-05-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_delete_department"),
        ("services", "0017_alter_departmentcompliance_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DepartmentCompliance",
            new_name="DirectorateCompliance",
        ),
        migrations.AlterModelOptions(
            name="directoratecompliance",
            options={
                "ordering": ["-service_month", "directorate"],
                "verbose_name": "التزام مديرية",
                "verbose_name_plural": "التزام المديريات",
            },
        ),
        migrations.RenameIndex(
            model_name="directoratecompliance",
            new_name="services_di_service_f44789_idx",
            old_name="services_de_service_fd876d_idx",
        ),
        migrations.RenameIndex(
            model_name="directoratecompliance",
            new_name="services_di_quality_e9bd3a_idx",
            old_name="services_de_quality_5f2e46_idx",
        ),
        migrations.AlterModelTable(
            name="directoratecompliance",
            table="services_directorate_compliance",
        ),
    ]
