# Generated by Django 5.0.2 on 2026-05-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_branch_centraldepartment_districtpolice_geodistrict_and_more"),
        (
            "personnel",
            "0020_remove_personnelmaster_personnel_m_directo_9053ba_idx_and_more",
        ),
        ("services", "0018_rename_departmentcompliance_directoratecompliance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ─── Phase 1: Remove old constraints & indexes ───
        migrations.RemoveConstraint(
            model_name="directoratecompliance",
            name="unique_compliance_per_org_month",
        ),
        migrations.RemoveConstraint(
            model_name="monthlysnapshot",
            name="unique_snapshot_per_org_month",
        ),
        migrations.RemoveIndex(
            model_name="exportlog",
            name="services_ex_directo_c6ea33_idx",
        ),
        migrations.RemoveIndex(
            model_name="rejectionlog",
            name="services_re_directo_3e2a3b_idx",
        ),
        # Remove old unique_together (references directorate)
        migrations.AlterUniqueTogether(
            name="directoratecompliance",
            unique_together=set(),
        ),

        # ─── Phase 2: Add new fields ───
        migrations.AddField(
            model_name="directoratecompliance",
            name="central_department",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_records",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="directoratecompliance",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_records",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="central_department",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="export_logs",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_logs",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="monthlysnapshot",
            name="central_department",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_snapshots",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="monthlysnapshot",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_snapshots",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationtask",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliation_tasks",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="rejectionlog",
            name="central_department",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejections",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="rejectionlog",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejections",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="serviceeventlog",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_events",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="stagingrecord",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staging_records",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_change_forms",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddField(
            model_name="webhookconfig",
            name="central_department",
            field=models.ForeignKey(
                blank=True,
                help_text="فارغ = جميع الإدارات",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_configs",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),

        # ─── Phase 3: Remove old fields ───
        migrations.RemoveField(model_name="exportlog", name="directorate"),
        migrations.RemoveField(model_name="exportlog", name="governorate"),
        migrations.RemoveField(model_name="monthlysnapshot", name="directorate"),
        migrations.RemoveField(model_name="monthlysnapshot", name="governorate"),
        migrations.RemoveField(model_name="reconciliationtask", name="governorate"),
        migrations.RemoveField(model_name="rejectionlog", name="directorate"),
        migrations.RemoveField(model_name="rejectionlog", name="governorate"),
        migrations.RemoveField(model_name="serviceeventlog", name="governorate"),
        migrations.RemoveField(model_name="stagingrecord", name="governorate"),
        migrations.RemoveField(model_name="statuschangeform", name="governorate"),
        migrations.RemoveField(model_name="webhookconfig", name="directorate"),
        migrations.RemoveField(model_name="directoratecompliance", name="directorate"),
        migrations.RemoveField(model_name="directoratecompliance", name="governorate"),

        # ─── Phase 4: Add new constraints, indexes, options ───
        migrations.AlterModelOptions(
            name="directoratecompliance",
            options={
                "ordering": ["-service_month", "central_department"],
                "verbose_name": "التزام إدارة",
                "verbose_name_plural": "التزام الإدارات",
            },
        ),
        migrations.AlterUniqueTogether(
            name="directoratecompliance",
            unique_together={("central_department", "service_month")},
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["central_department", "service_month"],
                name="services_ex_central_5a0b96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionlog",
            index=models.Index(
                fields=["central_department", "service_month"],
                name="services_re_central_435e37_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="directoratecompliance",
            constraint=models.UniqueConstraint(
                fields=("security_admin", "central_department", "service_month"),
                name="unique_compliance_per_org_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlysnapshot",
            constraint=models.UniqueConstraint(
                fields=("security_admin", "central_department", "service_month"),
                name="unique_snapshot_per_org_month",
            ),
        ),
    ]
