# Generated by Django 5.0.2 on 2026-05-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_alter_directoratecompliance_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="directoratecompliance",
            unique_together=set(),
        ),
    ]
