# Generated by Django 5.0.2 on 2026-07-03 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_securityadministration_geo_governorate"),
        ("personnel", "0033_alter_suggestedcorrection_correction_type"),
        ("services", "0020_alter_directoratecompliance_unique_together"),
        ("storage", "0006_alter_document_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("warning_verbal", "إنذار شفهي"),
                            ("warning_written", "إنذار كتابي"),
                            ("salary_deduction", "خصم من الراتب"),
                            ("suspension", "إيقاف عن العمل"),
                            ("demotion", "تخفيض رتبة"),
                            ("military_detention", "حبس عسكري"),
                            ("dismissal", "فصل من الخدمة"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع الجزاء",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("direct_superior", "رئيس مباشر"),
                            ("disciplinary_council", "مجلس تأديبي"),
                            ("judicial", "قضائي"),
                            ("ministry", "وزارة"),
                        ],
                        max_length=30,
                        verbose_name="مصدر القرار",
                    ),
                ),
                (
                    "issued_by_name",
                    models.CharField(
                        help_text="اسم الرئيس أو المجلس أو المحكمة التي أصدرت القرار",
                        max_length=200,
                        verbose_name="الجهة المُصدِرة",
                    ),
                ),
                (
                    "decision_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم القرار / الأمر"
                    ),
                ),
                ("issued_date", models.DateField(verbose_name="تاريخ صدور الجزاء")),
                ("effective_date", models.DateField(verbose_name="تاريخ سريانه")),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="يُملأ للإيقاف والحبس العسكري",
                        null=True,
                        verbose_name="المدة (بالأيام)",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف المخالفة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "قيد التنفيذ"),
                            ("executed", "منفذ"),
                            ("cancelled", "ملغى"),
                            ("appealed", "قيد الطعن"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "ministry_notified",
                    models.BooleanField(
                        default=False, verbose_name="تم إبلاغ الإدارة العامة"
                    ),
                ),
                (
                    "ministry_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإبلاغ"
                    ),
                ),
                (
                    "ministry_sent_batch",
                    models.CharField(
                        blank=True,
                        help_text="يُربط بدفعة رفع الخدمات الشهرية لمتابعة التنفيذ",
                        max_length=50,
                        verbose_name="رقم دفعة الإرسال",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات داخلية")),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disciplinary_actions",
                        to="storage.document",
                        verbose_name="المرفقات",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_disciplinary_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجّله",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplinary_actions",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد المعني",
                    ),
                ),
                (
                    "security_admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplinary_actions",
                        to="core.securityadministration",
                        verbose_name="إدارة الأمن",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزاء تأديبي",
                "verbose_name_plural": "الجزاءات التأديبية",
                "db_table": "services_disciplinary_action",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="AbsenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("unauthorized", "غياب بدون إذن"),
                            ("continuous_absence", "انقطاع متواصل"),
                            ("absent_in_monthly", "غائب في الخدمات الشهرية"),
                            ("suspended", "موقوف بقرار"),
                        ],
                        max_length=30,
                        verbose_name="نوع الغياب",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="من تاريخ")),
                (
                    "to_date",
                    models.DateField(
                        blank=True,
                        help_text="اتركه فارغاً إذا لم يعد الفرد بعد",
                        null=True,
                        verbose_name="إلى تاريخ",
                    ),
                ),
                (
                    "reported_by_unit",
                    models.CharField(max_length=200, verbose_name="الوحدة المُبلِّغة"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("unit_report", "بلاغ الوحدة"),
                            ("monthly_sheet", "كشف الخدمات الشهري"),
                            ("directorate", "كشف المديرية"),
                            ("branch", "كشف الفرع"),
                        ],
                        max_length=30,
                        verbose_name="مصدر البلاغ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("notified_ministry", "تم الإبلاغ للإدارة العامة"),
                            ("action_taken", "تم اتخاذ إجراء"),
                            ("closed", "مغلق — عاد للعمل"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "ministry_notified",
                    models.BooleanField(
                        default=False, verbose_name="تم الإبلاغ للإدارة العامة"
                    ),
                ),
                (
                    "ministry_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإبلاغ"
                    ),
                ),
                (
                    "ministry_sent_batch",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم دفعة الإرسال"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_absence_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجّله",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absence_records",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد الغائب",
                    ),
                ),
                (
                    "security_admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absence_records",
                        to="core.securityadministration",
                        verbose_name="إدارة الأمن",
                    ),
                ),
                (
                    "linked_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absence_records",
                        to="services.disciplinaryaction",
                        verbose_name="الجزاء المترتب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل غياب",
                "verbose_name_plural": "سجلات الغياب",
                "db_table": "services_absence_record",
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryCouncilVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "verdict_ref",
                    models.CharField(max_length=100, verbose_name="رقم الحكم"),
                ),
                ("verdict_date", models.DateField(verbose_name="تاريخ صدور الحكم")),
                (
                    "verdict_type",
                    models.CharField(
                        choices=[
                            ("acquittal", "براءة"),
                            ("warning", "إنذار"),
                            ("demotion", "تخفيض رتبة"),
                            ("suspension", "إيقاف مؤقت"),
                            ("dismissal", "فصل من الخدمة"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع الحكم",
                    ),
                ),
                ("verdict_details", models.TextField(verbose_name="تفاصيل الحكم")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "مستلَم — في انتظار الإيداع"),
                            ("filed", "مودَع في ملف المعني"),
                            ("sent_ministry", "أُرسِل للإدارة العامة"),
                            ("executed", "منفَّذ"),
                            ("appealed", "قيد الطعن / الاستئناف"),
                        ],
                        default="received",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "ministry_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="تاريخ الإرسال للإدارة العامة",
                    ),
                ),
                (
                    "ministry_sent_batch",
                    models.CharField(
                        blank=True,
                        help_text="يُربط بدفعة رفع الخدمات لمتابعة ما لم يُرسَل بعد",
                        max_length=50,
                        verbose_name="رقم دفعة الإرسال",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disciplinary_verdicts",
                        to="storage.document",
                        verbose_name="نسخ الحكم والمرفقات",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_verdicts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سجّله",
                    ),
                ),
                (
                    "linked_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verdicts",
                        to="services.disciplinaryaction",
                        verbose_name="الجزاء المترتب على الحكم",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplinary_verdicts",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد المحكوم عليه",
                    ),
                ),
                (
                    "security_admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplinary_verdicts",
                        to="core.securityadministration",
                        verbose_name="إدارة الأمن",
                    ),
                ),
            ],
            options={
                "verbose_name": "حكم تأديبي",
                "verbose_name_plural": "الأحكام التأديبية",
                "db_table": "services_disciplinary_verdict",
                "ordering": ["-verdict_date"],
            },
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["personnel", "status"], name="services_di_personn_b9dc80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["action_type", "status"], name="services_di_action__273476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["security_admin", "issued_date"],
                name="services_di_securit_908c16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryaction",
            index=models.Index(
                fields=["ministry_notified"], name="services_di_ministr_6a9dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="absencerecord",
            index=models.Index(
                fields=["personnel", "status"], name="services_ab_personn_a17a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="absencerecord",
            index=models.Index(
                fields=["security_admin", "from_date"],
                name="services_ab_securit_f32a10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="absencerecord",
            index=models.Index(
                fields=["absence_type"], name="services_ab_absence_884780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="absencerecord",
            index=models.Index(
                fields=["ministry_notified"], name="services_ab_ministr_be8a8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycouncilverdict",
            index=models.Index(
                fields=["personnel", "status"], name="services_di_personn_7b983e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycouncilverdict",
            index=models.Index(
                fields=["security_admin", "verdict_date"],
                name="services_di_securit_120c63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycouncilverdict",
            index=models.Index(
                fields=["verdict_type"], name="services_di_verdict_62a868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycouncilverdict",
            index=models.Index(
                fields=["ministry_sent_at"], name="services_di_ministr_8b5781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinarycouncilverdict",
            index=models.Index(
                fields=["ministry_sent_batch"], name="services_di_ministr_95333a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="disciplinarycouncilverdict",
            constraint=models.UniqueConstraint(
                fields=("verdict_ref", "security_admin"),
                name="unique_verdict_ref_per_admin",
            ),
        ),
    ]
