# Generated by Django 5.0.2 on 2026-07-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_disciplinaryaction_absencerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الخدمة')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('category', models.CharField(choices=[('military', 'حركات الأفراد والتعيينات'), ('financial', 'الخدمات المالية والرواتب'), ('disciplinary', 'شؤون الانضباط والإجراءات'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='فئة الخدمة')),
                ('icon', models.CharField(max_length=50, verbose_name='أيقونة الخدمة (Lucide)')),
                ('form_type', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نوع الاستمارة المرتبطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='تتطلب موافقات')),
                ('is_repeatable', models.BooleanField(default=True, verbose_name='قابلة للتكرار')),
                ('expected_duration_hours', models.IntegerField(default=48, verbose_name='المدة المتوقعة (ساعات)')),
                ('attachments_count', models.IntegerField(default=0, verbose_name='عدد المرفقات المتوقعة')),
                ('target_audience', models.CharField(default='الكل', max_length=100, verbose_name='الفئة المستهدفة')),
                ('fields_schema', models.JSONField(blank=True, default=dict, verbose_name='مخطط الحقول (JSON)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'دليل خدمة',
                'verbose_name_plural': 'دليل الخدمات',
                'db_table': 'services_service_catalog',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='statuschangeform',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='متأخر'),
        ),
        migrations.AddField(
            model_name='statuschangeform',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='statuschangeform',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي (SLA)'),
        ),
        migrations.AlterField(
            model_name='statuschangeform',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_services', 'بانتظار قسم الخدمات'), ('pending_hr', 'بانتظار مدير الموارد البشرية'), ('pending_director', 'بانتظار المدير العام'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('returned', 'مُرجع — بحاجة لتعديل')], default='draft', max_length=20, verbose_name='حالة الاستمارة'),
        ),
        migrations.CreateModel(
            name='FormChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العنصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('stage', models.CharField(max_length=50, verbose_name='مرحلة الاعتماد')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('is_checked', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اكتمل بواسطة')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='services.statuschangeform', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر تحقق',
                'verbose_name_plural': 'قوائم التحقق',
                'db_table': 'services_form_checklist',
                'ordering': ['form', 'stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('action', models.CharField(choices=[('created', 'إنشاء'), ('submitted', 'تقديم'), ('approved', 'اعتماد'), ('rejected', 'رفض'), ('returned', 'إرجاع'), ('note_added', 'إضافة ملاحظة'), ('updated', 'تحديث بيانات'), ('checklist_checked', 'إكمال تحقق')], max_length=30, verbose_name='الإجراء')),
                ('from_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='إلى حالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('expected_duration_hours', models.IntegerField(blank=True, null=True, verbose_name='المدة المتوقعة (ساعات)')),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المدة الفعلية (ساعات)')),
                ('sla_status', models.CharField(choices=[('on_time', 'في الوقت'), ('at_risk', 'معرض للخطر'), ('overdue', 'متأخر'), ('na', 'غير متاح')], default='na', max_length=20, verbose_name='حالة SLA')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='متأخر')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='services.statuschangeform', verbose_name='الطلب')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
            ],
            options={
                'verbose_name': 'سجل حدث',
                'verbose_name_plural': 'سجلات الأحداث',
                'db_table': 'services_form_event_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(verbose_name='محتوى الملاحظة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='أضيفت بواسطة')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_notes', to='services.statuschangeform', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'ملاحظة على الطلب',
                'verbose_name_plural': 'ملاحظات الطلبات',
                'db_table': 'services_form_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('return_reason', models.CharField(choices=[('missing_attachments', 'نقص المرفقات'), ('incorrect_data', 'بيانات غير صحيحة'), ('incomplete_form', 'نموذج غير مكتمل'), ('other', 'أخرى')], max_length=30, verbose_name='سبب الإرجاع')),
                ('return_details', models.TextField(blank=True, verbose_name='تفاصيل السبب')),
                ('from_status', models.CharField(max_length=50, verbose_name='من مرحلة')),
                ('to_status', models.CharField(max_length=50, verbose_name='إلى مرحلة')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم حل المشكلة')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='services.statuschangeform', verbose_name='الطلب')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_forms', to=settings.AUTH_USER_MODEL, verbose_name='أُرجع بواسطة')),
            ],
            options={
                'verbose_name': 'سجل إرجاع',
                'verbose_name_plural': 'سجلات الإرجاع',
                'db_table': 'services_form_return_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('stage', models.CharField(max_length=50, verbose_name='مرحلة الاعتماد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العنصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='services.servicecatalog', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'قالب عنصر تحقق',
                'verbose_name_plural': 'قوالب عناصر التحقق',
                'db_table': 'services_checklist_template',
                'ordering': ['service', 'stage', 'order'],
            },
        ),
        migrations.AddField(
            model_name='statuschangeform',
            name='service_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='services.servicecatalog', verbose_name='دليل الخدمة المرتبط'),
        ),
        migrations.CreateModel(
            name='ServicePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الشرط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('validation_type', models.CharField(choices=[('age_min', 'الحد الأدنى للعمر'), ('age_max', 'الحد الأقصى للعمر'), ('service_years_min', 'الحد الأدنى لسنوات الخدمة'), ('status_check', 'التحقق من الحالة الحالية'), ('custom', 'تحقق مخصص')], max_length=50, verbose_name='نوع التحقق')),
                ('validation_value', models.CharField(max_length=255, verbose_name='القيمة المطلوبة')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='services.servicecatalog', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'شرط مسبق',
                'verbose_name_plural': 'الشروط المسبقة',
                'db_table': 'services_service_prerequisite',
                'ordering': ['service', 'order'],
            },
        ),
    ]
