# Generated by Django 5.0.2 on 2026-07-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_servicecatalog_statuschangeform_is_overdue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المرحلة')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المرحلة')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة المرحلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
            ],
            options={
                'verbose_name': 'مرحلة سير العمل',
                'verbose_name_plural': 'مراحل سير العمل',
                'db_table': 'services_workflow_stage',
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب الخطوة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخطوة')),
                ('is_final_step', models.BooleanField(default=False, verbose_name='خطوة نهائية (اعتماد نهائي)')),
                ('is_execution_step', models.BooleanField(default=False, verbose_name='خطوة تنفيذ (إصدار)')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='تتطلب موافقة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='services.servicecatalog', verbose_name='الخدمة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_steps', to='services.workflowstage', verbose_name='المرحلة العامة')),
            ],
            options={
                'verbose_name': 'خطوة سير عمل الخدمة',
                'verbose_name_plural': 'خطوات سير عمل الخدمات',
                'db_table': 'services_service_workflow_step',
                'ordering': ['service', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceworkflowstep',
            constraint=models.UniqueConstraint(fields=('service', 'order'), name='unique_service_workflow_order'),
        ),
    ]
