# Generated by Django 5.0.2 on 2026-07-06 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_workflowstage_serviceworkflowstep_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuschangeform",
            name="director_approved_at",
        ),
        migrations.RemoveField(
            model_name="statuschangeform",
            name="director_approved_by",
        ),
        migrations.RemoveField(
            model_name="statuschangeform",
            name="hr_approved_at",
        ),
        migrations.RemoveField(
            model_name="statuschangeform",
            name="hr_approved_by",
        ),
        migrations.RemoveField(
            model_name="statuschangeform",
            name="services_approved_at",
        ),
        migrations.RemoveField(
            model_name="statuschangeform",
            name="services_approved_by",
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_forms",
                to="services.serviceworkflowstep",
                verbose_name="المرحلة الحالية",
            ),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="workflow_log",
            field=models.JSONField(
                default=list,
                help_text="سجل ديناميكي لمن اعتمد الاستمارة في كل مرحلة ومتى",
                verbose_name="سجل الاعتمادات",
            ),
        ),
        migrations.AlterField(
            model_name="statuschangeform",
            name="form_type",
            field=models.CharField(max_length=100, verbose_name="نوع الاستمارة"),
        ),
        migrations.AlterField(
            model_name="statuschangeform",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("in_progress", "قيد الإجراء"),
                    ("approved", "معتمد"),
                    ("rejected", "مرفوض"),
                    ("returned", "مُرجع — بحاجة لتعديل"),
                ],
                default="draft",
                max_length=20,
                verbose_name="حالة الاستمارة",
            ),
        ),
    ]
