# Generated by Django 5.0.2 on 2026-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_remove_statuschangeform_director_approved_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecatalog",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="وصف الخدمة"),
        ),
    ]
