# Generated by Django 5.2.15 on 2026-07-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0025_alter_servicecatalog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="approval_type",
            field=models.CharField(
                choices=[
                    ("internal", "موافقة داخلية"),
                    ("external", "موافقة خارجية"),
                    ("none", "لا تتطلب موافقة"),
                ],
                default="internal",
                help_text="هل الطلب يحتاج موافقة داخلية (مدير) أو خارجية (وزارة) أو لا يحتاج",
                max_length=20,
                verbose_name="نوع الموافقة",
            ),
        ),
        migrations.AddField(
            model_name="servicecatalog",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="مقفلة"),
        ),
        migrations.AddField(
            model_name="servicecatalog",
            name="lock_reason",
            field=models.TextField(blank=True, default="", verbose_name="سبب القفل"),
        ),
        migrations.AddField(
            model_name="servicecatalog",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("form", "استمارة"),
                    ("correction", "تصحيح بيانات"),
                    ("rank_settlement", "ترقية / تسوية رتبة"),
                    ("disciplinary", "جزاء تأديبي"),
                    ("security", "أمان ومزامنة"),
                    ("other", "أخرى"),
                ],
                default="form",
                help_text="يحدد التبويب الذي تظهر فيه الخدمة في دليل الخدمات",
                max_length=30,
                verbose_name="تصنيف الخدمة",
            ),
        ),
    ]
