# Generated by Django 5.0.2 on 2026-07-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0026_add_approval_type_and_service_type"),
        ("storage", "0006_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuschangeform",
            name="is_printed",
            field=models.BooleanField(default=False, verbose_name="تمت الطباعة"),
        ),
        migrations.AddField(
            model_name="statuschangeform",
            name="ministry_approval_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ministry_approvals",
                to="storage.document",
                verbose_name="مستند موافقة الوزارة",
            ),
        ),
    ]
