# Generated by Django 5.2.15 on 2026-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_statuschangeform_is_printed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="attachments_schema",
            field=models.JSONField(
                blank=True, default=list, verbose_name="مخطط المرفقات الإلزامية (JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="statuschangeform",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("retirement_age", "بلوغ السن القانوني"),
                    ("death", "وفاة"),
                    ("missing", "مفقود"),
                    ("medical_unfit", "عدم لياقة صحية"),
                    ("end_of_service", "إنهاء مدة"),
                    ("retired", "محال للتقاعد"),
                    ("imprisoned", "مسجون"),
                    ("escort", "مرافق / معيات"),
                    ("martyr", "شهيد"),
                    ("study_leave", "مفرغ للدراسة"),
                    ("seconded", "منتدب"),
                ],
                max_length=100,
                verbose_name="نوع الاستمارة",
            ),
        ),
    ]
