# Generated by Django 5.2.15 on 2026-07-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_servicecatalog_attachments_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="execution_action",
            field=models.CharField(
                choices=[
                    ("UPDATE_STATUS", "تغيير الحالة (استمارات إثبات الحالة)"),
                    ("UPDATE_RANK", "تحديث الرتبة (ترقيات)"),
                    ("SECURITY_RESTRICT", "قيد أمني"),
                    ("NONE", "للتوثيق فقط (لا يوجد تأثير)"),
                ],
                default="UPDATE_STATUS",
                help_text="ما هو الإجراء الفعلي الذي سيتم تطبيقه على قاعدة البيانات بعد الاعتماد؟",
                max_length=30,
                verbose_name="الإجراء التنفيذي",
            ),
        ),
    ]
