# Generated by Django 5.2.15 on 2026-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_servicecatalog_execution_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="execution_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="إعدادات متغيرة تعتمد على نوع الإجراء (مثلاً: الحالة المستهدفة، مدة القيد الأمن)",
                verbose_name="إعدادات التنفيذ",
            ),
        ),
    ]
