# Generated by Django 5.0.2 on 2026-07-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_statuschangeform_form_type'),
        ('services', '0030_servicecatalog_execution_config'),
    ]

    operations = [
    ]
