# Generated by Django 5.0.2 on 2026-07-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0031_merge_20260708_1940"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BIDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المصدر")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("orm_model", "نموذج ORM"),
                            ("db_view", "عرض قاعدة بيانات (View)"),
                            ("raw_sql", "استعلام مباشر (Raw SQL)"),
                        ],
                        default="orm_model",
                        max_length=50,
                        verbose_name="نوع المصدر",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="اسم الجدول، الـ View، أو مسار الـ ORM Model (مثال: personnel.PersonnelMaster)",
                        max_length=255,
                        verbose_name="الهدف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
            ],
            options={
                "verbose_name": "مصدر بيانات BI",
                "verbose_name_plural": "مصادر بيانات BI",
                "db_table": "services_bi_datasource",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="execution_action",
            field=models.CharField(
                choices=[
                    ("UPDATE_STATUS", "تغيير الحالة (استمارات إثبات الحالة)"),
                    ("UPDATE_RANK", "تحديث الرتبة (ترقيات)"),
                    ("PERSONNEL_TO_OFFICER", "تحديث رتبة ورقم عسكري (ضباط)"),
                    ("SECURITY_RESTRICT", "قيد أمني"),
                    ("NONE", "للتوثيق فقط (لا يوجد تأثير)"),
                ],
                default="UPDATE_STATUS",
                help_text="ما هو الإجراء الفعلي الذي سيتم تطبيقه على قاعدة البيانات بعد الاعتماد؟",
                max_length=30,
                verbose_name="الإجراء التنفيذي",
            ),
        ),
        migrations.CreateModel(
            name="EnterpriseReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان التقرير"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="الرمز المرجعي")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف التقرير"),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict,
                        help_text="يحتوي على Columns, Filters, Layout, Permissions",
                        verbose_name="مخطط التكوين (JSON Schema)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_enterprise_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprise_reports",
                        to="services.bidatasource",
                        verbose_name="مصدر البيانات",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير BI مؤسسي",
                "verbose_name_plural": "تقارير BI مؤسسية",
                "db_table": "services_enterprise_report_template",
                "ordering": ["-created_at"],
            },
        ),
    ]
