# Generated by Django 5.2.15 on 2026-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0032_bidatasource_alter_servicecatalog_execution_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stagingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("pending_external", "في انتظار اعتماد الوزارة"),
                    ("approved", "موافق عليه"),
                    ("rejected", "مرفوض"),
                ],
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
