# Generated by Django 5.0.2 on 2026-07-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_stagingrecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاستمارة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرمز (Slug)')),
                ('category', models.CharField(default='رسمية', max_length=100, verbose_name='التصنيف')),
                ('is_preset', models.BooleanField(default=False, verbose_name='قالب جاهز (Preset)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('header_columns', models.PositiveSmallIntegerField(default=3, verbose_name='أعمدة الترويسة')),
                ('header_blocks', models.JSONField(default=list, help_text='مصفوفة من النصوص (HTML) لكل عمود', verbose_name='محتوى الترويسة')),
                ('body_content', models.TextField(blank=True, verbose_name='محتوى الاستمارة الرئيسي')),
                ('footer_columns', models.PositiveSmallIntegerField(default=1, verbose_name='أعمدة التذييل')),
                ('footer_blocks', models.JSONField(default=list, help_text='مصفوفة من النصوص (HTML) لكل عمود', verbose_name='محتوى التذييل')),
                ('page_size', models.CharField(default='A4', max_length=20, verbose_name='حجم الصفحة')),
                ('orientation', models.CharField(default='portrait', max_length=20, verbose_name='اتجاه الصفحة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_form_templates', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'استمارة ديناميكية',
                'verbose_name_plural': 'الاستمارات الديناميكية',
                'db_table': 'services_document_form_template',
                'ordering': ['name'],
            },
        ),
    ]
