# Generated by Django 5.2.15 on 2026-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0034_documentformtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecatalog",
            name="execution_action",
            field=models.CharField(
                choices=[
                    ("UPDATE_STATUS", "تغيير الحالة (استمارات إثبات الحالة)"),
                    ("UPDATE_RANK", "تحديث الرتبة (ترقيات)"),
                    ("PERSONNEL_TO_OFFICER", "تحديث رتبة ورقم عسكري (ضباط)"),
                    ("SECURITY_RESTRICT", "قيد أمني"),
                    ("SECURITY_SYNC", "مزامنة أمنية"),
                    ("CORRECTION_NAME", "تصحيح اسم"),
                    ("CORRECTION_MILITARY_NUM", "تصحيح رقم عسكري"),
                    ("CORRECTION_NATIONAL_ID", "تصحيح رقم وطني"),
                    ("DISCIPLINARY_ADD", "إضافة جزاء تأديبي"),
                    ("DISCIPLINARY_REMOVE", "رفع جزاء تأديبي"),
                    ("NONE", "للتوثيق فقط (لا يوجد تأثير)"),
                ],
                default="UPDATE_STATUS",
                help_text="ما هو الإجراء الفعلي الذي سيتم تطبيقه على قاعدة البيانات بعد الاعتماد؟",
                max_length=30,
                verbose_name="الإجراء التنفيذي",
            ),
        ),
    ]
