# Generated by Django 5.2.15 on 2026-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0035_alter_servicecatalog_execution_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalog",
            name="disabled_engine_rules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="قائمة بمعرفات القواعد (Rule IDs) التي تم إيقافها لهذه الخدمة",
                verbose_name="قواعد المحرك الموقوفة",
            ),
        ),
    ]
