# Generated by Django 5.0.2 on 2026-04-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_advanced_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="اسم الإدارة العامة"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب المدير"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "إدارة عامة",
                "verbose_name_plural": "الإدارات العامة",
                "db_table": "core_directorate",
                "ordering": ["governorate", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المحافظة"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="الكود",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "محافظة",
                "verbose_name_plural": "المحافظات",
                "db_table": "core_governorate",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القسم")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب رئيس القسم"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "directorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="core.directorate",
                        verbose_name="الإدارة العامة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "db_table": "core_division",
                "ordering": ["directorate", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="directorate",
            name="governorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directorates",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الوحدة")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب رئيس الوحدة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.division",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "وحدة",
                "verbose_name_plural": "الوحدات",
                "db_table": "core_unit",
                "ordering": ["division", "order", "name"],
            },
        ),
    ]
