# Generated by Django 5.0.2 on 2026-05-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_force_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateTransitionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False,
                        help_text="هل يجب رفع مستند رسمي لإتمام الانتقال",
                        verbose_name="يتطلب مرفق",
                    ),
                ),
                (
                    "required_document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='مثل: ["death_cert", "ministry_order", "medical_report"]',
                        verbose_name="أنواع المرفقات المطلوبة",
                    ),
                ),
                (
                    "requires_dual_auth",
                    models.BooleanField(
                        default=False,
                        help_text="عمليات فائقة الحساسية مثل الاستشهاد والوفاة",
                        verbose_name="يتطلب تفويض مزدوج",
                    ),
                ),
                (
                    "requires_status_change_form",
                    models.BooleanField(
                        default=False,
                        help_text="مثل استمارة وفاة أو تقاعد",
                        verbose_name="يتطلب استمارة إثبات حالة",
                    ),
                ),
                (
                    "min_role_priority",
                    models.IntegerField(
                        default=0,
                        help_text="0=أي مستخدم مصرح, 50=رئيس خدمات, 100=مدير نظام",
                        verbose_name="الحد الأدنى لأولوية الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="وصف القاعدة أو الإشارة للأمر الوزاري",
                        verbose_name="ملاحظات",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة انتقال حالة",
                "verbose_name_plural": "قواعد انتقال الحالات",
                "db_table": "core_state_transition_rule",
                "ordering": ["from_status", "to_status"],
            },
        ),
        migrations.RenameIndex(
            model_name="forcetype",
            new_name="core_force__categor_726d98_idx",
            old_name="core_force__categor_idx",
        ),
        migrations.RenameIndex(
            model_name="forcetype",
            new_name="core_force__rank_ty_6f1144_idx",
            old_name="core_force__rank_ty_idx",
        ),
        migrations.AddField(
            model_name="statetransitionrule",
            name="from_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions_from",
                to="core.servicestatus",
                verbose_name="من حالة",
            ),
        ),
        migrations.AddField(
            model_name="statetransitionrule",
            name="to_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions_to",
                to="core.servicestatus",
                verbose_name="إلى حالة",
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionrule",
            index=models.Index(
                fields=["from_status"], name="core_state__from_st_dcc896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionrule",
            index=models.Index(
                fields=["to_status"], name="core_state__to_stat_fe191c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statetransitionrule",
            index=models.Index(
                fields=["is_active"], name="core_state__is_acti_0f523e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statetransitionrule",
            unique_together={("from_status", "to_status")},
        ),
    ]
