# Generated by Django 5.0.2 on 2026-05-16 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_move_to_core_rbac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
            },
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "verbose_name": "صلاحية دور",
                "verbose_name_plural": "صلاحيات الأدوار",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "دور مستخدم",
                "verbose_name_plural": "أدوار المستخدمين",
            },
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="core_login__action_6b228c_idx",
            old_name="core_login_action_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="core_login__user_id_0ab6ff_idx",
            old_name="core_login_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="loginauditlog",
            new_name="core_login__timesta_b7be6f_idx",
            old_name="core_login_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="permission",
            new_name="core_permis_module_323302_idx",
            old_name="core_perm_module_idx",
        ),
        migrations.RenameIndex(
            model_name="permission",
            new_name="core_permis_is_acti_04a15b_idx",
            old_name="core_perm_active_idx",
        ),
        migrations.RenameIndex(
            model_name="role",
            new_name="core_role_code_41eecc_idx",
            old_name="core_role_code_idx",
        ),
        migrations.RenameIndex(
            model_name="role",
            new_name="core_role_is_acti_cf5dc6_idx",
            old_name="core_role_active_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                help_text="مثل: CREATE, UPDATE, DELETE, LOGIN, EXPORT",
                max_length=50,
                verbose_name="العملية",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="عنوان IP"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100, verbose_name="اسم النموذج"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="البيانات الجديدة"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=100, verbose_name="معرف الكائن"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="البيانات القديمة"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="signature",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="التوقيع الرقمي"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, default="", verbose_name="User Agent"),
        ),
        migrations.AlterField(
            model_name="loginauditlog",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "لا يوجد"),
                    ("invalid_password", "كلمة مرور خاطئة"),
                    ("account_locked", "حساب مغلق"),
                    ("account_disabled", "حساب معطل"),
                    ("user_not_found", "مستخدم غير موجود"),
                    ("two_factor_failed", "فشل التحقق الثنائي"),
                ],
                default="",
                max_length=30,
                verbose_name="سبب الفشل",
            ),
        ),
        migrations.AlterField(
            model_name="loginauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="action_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="رابط الإجراء"
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="extra_data",
            field=models.JSONField(blank=True, null=True, verbose_name="بيانات إضافية"),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="مقروء"),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="message",
            field=models.TextField(verbose_name="الرسالة"),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("STAGING_SUBMITTED", "كشف جديد"),
                    ("RECONCILIATION_NEEDED", "مطابقة مطلوبة"),
                    ("STATUS_CHANGE", "تغيير حالة"),
                    ("DUAL_AUTH_REQUIRED", "تفويض مزدوج مطلوب"),
                    ("DUAL_AUTH_APPROVED", "تفويض مزدوج مُعتمد"),
                    ("DUAL_AUTH_REJECTED", "تفويض مزدوج مرفوض"),
                    ("MONTH_CLOSED", "إقفال شهر"),
                    ("IMPORT_COMPLETED", "اكتمال استيراد"),
                    ("EXPORT_COMPLETED", "اكتمال تصدير"),
                    ("SYSTEM", "إشعار نظامي"),
                    ("WARNING", "تحذير"),
                    ("ERROR", "خطأ"),
                ],
                max_length=30,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "منخفض"),
                    ("normal", "عادي"),
                    ("high", "مرتفع"),
                    ("urgent", "عاجل"),
                ],
                default="normal",
                max_length=10,
                verbose_name="الأولوية",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ القراءة"
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="related_object_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="معرف الكائن"
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="related_object_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نوع الكائن"
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="target_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المستهدف",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="title",
            field=models.CharField(max_length=200, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المُرسل",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.CharField(
                help_text="مثل: view, create, edit, delete, approve",
                max_length=50,
                verbose_name="الفعل",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                help_text="يُبنى تلقائياً: module.action.scope",
                max_length=100,
                unique=True,
                verbose_name="الكود",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                help_text="مثل: personnel, services, audit, security",
                max_length=50,
                verbose_name="النظام الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="scope",
            field=models.CharField(
                default="all",
                help_text="مثل: all, own, department, governorate",
                max_length=50,
                verbose_name="النطاق",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="additional_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_users",
                through="core.UserRole",
                to="core.role",
                verbose_name="أدوار إضافية",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات المدير"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="can_override_lock",
            field=models.BooleanField(
                default=False, verbose_name="صلاحية إلغاء الإقفال"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.department",
                verbose_name="الإدارة",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.directorate",
                verbose_name="الإدارة العامة",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.division",
                verbose_name="القسم",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.IntegerField(default=0, verbose_name="محاولات دخول فاشلة"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_account_locked",
            field=models.BooleanField(default=False, verbose_name="حساب مغلق"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "الإنجليزية")],
                default="ar",
                max_length=5,
                verbose_name="اللغة",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="آخر IP"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_user_agent",
            field=models.TextField(blank=True, verbose_name="آخر User Agent"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="مقفل حتى"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="requires_two_factor",
            field=models.BooleanField(default=False, verbose_name="يتطلب تحقق ثنائي"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="supervised_departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="supervisors",
                to="core.department",
                verbose_name="الإدارات المُشرف عليها",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="supervises_all_departments",
            field=models.BooleanField(
                default=False, verbose_name="يشرف على جميع الإدارات"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.unit",
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تنتهي في"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="core_audit__action_82b39f_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name"], name="core_audit__model_n_7fcf39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="core_audit__user_id_66db5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="core_audit__timesta_75f997_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginauditlog",
            index=models.Index(
                fields=["ip_address"], name="core_login__ip_addr_95cc4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginauditlog",
            index=models.Index(
                fields=["username_attempted"], name="core_login__usernam_751304_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["target_user", "is_read"], name="core_notifi_target__39bf97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["notification_type"], name="core_notifi_notific_cbfe88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["created_at"], name="core_notifi_created_d0c445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecord",
            index=models.Index(
                fields=["priority"], name="core_notifi_priorit_8208cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["module", "action"], name="core_permis_module_568e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="core_user_p_role_id_fbfdf4_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["department"], name="core_user_p_departm_41a184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["is_account_locked"], name="core_user_p_is_acco_d300f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["governorate"], name="core_user_p_governo_369664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="core_user_r_user_id_4f1ede_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="core_user_r_role_id_72af9d_idx"),
        ),
    ]
