# Generated by Django 5.0.2 on 2026-05-16 22:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_loginauditlog_login_audit_timestamp_brin_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["timestamp"], name="audit_timestamp_brin_idx"
            ),
        ),
    ]
