# Generated by Django 5.0.2 on 2026-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auditlog_audit_timestamp_brin_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="رمز فريد بالإنجليزية — مثال: download_from_marib",
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="الصياغة الرسمية الموحدة التي ستظهر في الكشوفات",
                        max_length=300,
                        unique=True,
                        verbose_name="النص الموحد",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="شرح مختصر لمتى يُستخدم هذا المتغير",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "legacy_aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="صياغات مختلفة من الإكسل القديم تشير لنفس المعنى — للمطابقة التلقائية عند الاستيراد",
                        verbose_name="المسميات القديمة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "قيمة متغير شهري شائعة",
                "verbose_name_plural": "القيم الشائعة للمتغيرات الشهرية",
                "db_table": "core_variable_type",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="core_variab_is_acti_ee6b0d_idx"
                    )
                ],
            },
        ),
    ]
