# Generated by Django 5.0.2 on 2026-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization",
            "0002_remove_userprofile_authorizati_departm_00b76e_idx_and_more",
        ),
        ("core", "0020_alter_department_unique_together_and_more"),
        ("services", "0017_alter_departmentcompliance_options_and_more"),
        ("security", "0007_remove_role_userprofile_to_core"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
