# Generated by Django 5.0.2 on 2026-05-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_delete_location_alter_division_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION prevent_locked_snapshot_modification()
            RETURNS TRIGGER AS $$
            BEGIN
                -- السماح بفتح القفل (locked يتغير من True إلى False)
                -- ولكن منع أي تعديل آخر (البيانات، الشهر، إلخ) إذا كان القفل موجوداً ولم يتم إزالته
                IF OLD.locked = TRUE AND NEW.locked = TRUE AND OLD IS DISTINCT FROM NEW THEN
                    RAISE EXCEPTION 'لا يمكن تعديل بيانات اللقطة المقفلة (%). لإجراء تعديلات يجب إلغاء الإقفال (Unlock) أولاً.', OLD.service_month
                        USING ERRCODE = '23514',
                              HINT = 'اللقطات المقفلة محمية من التعديل المباشر.';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION prevent_locked_snapshot_modification()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.locked = TRUE THEN
                    RAISE EXCEPTION 'لا يمكن تعديل اللقطة الشهرية المقفلة (%). الشهر مقفل نهائياً.', OLD.service_month
                        USING ERRCODE = '23514',
                              HINT = 'اللقطات المقفلة محمية من التعديل';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
    ]
