# Generated by Django 5.0.2 on 2026-05-16 22:52

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_auditlog_audit_timestamp_brin_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الحالة")),
                ("code", models.CharField(max_length=50, verbose_name="رمز الحالة")),
                (
                    "state_type",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("review", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("archived", "مؤرشف"),
                        ],
                        default="review",
                        max_length=20,
                        verbose_name="نوع الحالة",
                    ),
                ),
                (
                    "is_initial",
                    models.BooleanField(default=False, verbose_name="حالة البداية"),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="حالة النهاية"),
                ),
            ],
            options={
                "verbose_name": "حالة",
                "verbose_name_plural": "الحالات",
                "db_table": "workflow_state",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="اسم العملية"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز العملية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "مسار عمل",
                "verbose_name_plural": "مسارات العمل",
                "db_table": "workflow_master",
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "min_approvals",
                    models.PositiveIntegerField(
                        default=1, verbose_name="عدد الموافقات المطلوبة"
                    ),
                ),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        default=48, verbose_name="الحد الأقصى للساعات (SLA)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="الترتيب"),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.role",
                        verbose_name="الدور المطلوب",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_approval_step",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "notify_only",
                    models.BooleanField(
                        default=True, verbose_name="إشعار فقط (بدون نقل الصلاحية)"
                    ),
                ),
                (
                    "approval_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="workflows.approvalstep",
                    ),
                ),
                (
                    "escalate_to_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.role",
                        verbose_name="الدور المُصعّد إليه",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_escalation_rule",
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="اسم الانتقال (الزر)"
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflows.state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflows.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "انتقال",
                "verbose_name_plural": "الانتقالات",
                "db_table": "workflow_transition",
            },
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="transition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_steps",
                to="workflows.transition",
            ),
        ),
        migrations.CreateModel(
            name="TransitionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="الشروط الديناميكية"
                    ),
                ),
                (
                    "transition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule",
                        to="workflows.transition",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_transition_rule",
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(max_length=100, verbose_name="نوع الكيان"),
                ),
                (
                    "context_id",
                    models.CharField(max_length=100, verbose_name="معرف الكيان"),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_instances",
                        to="workflows.state",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب عملية",
                "verbose_name_plural": "طلبات العمليات",
                "db_table": "workflow_instance",
            },
        ),
        migrations.CreateModel(
            name="InstanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="تعليقات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_from_state",
                        to="workflows.state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_to_state",
                        to="workflows.state",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_history",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_instance_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="رقم الإصدار"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="نشط حالياً"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "إصدار المسار",
                "verbose_name_plural": "إصدارات المسارات",
                "db_table": "workflow_version",
                "unique_together": {("workflow", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workflows.workflowversion",
            ),
        ),
        migrations.AddField(
            model_name="transition",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="workflows.workflowversion",
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="workflows.workflowversion",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWorkflowInstance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ التحديث"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "context_type",
                    models.CharField(max_length=100, verbose_name="نوع الكيان"),
                ),
                (
                    "context_id",
                    models.CharField(max_length=100, verbose_name="معرف الكيان"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="workflows.state",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="workflows.workflowversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical طلب عملية",
                "verbose_name_plural": "historical طلبات العمليات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["context_type", "context_id"],
                name="workflow_in_context_36edc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["current_state"], name="workflow_in_current_6d55ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transition",
            unique_together={("version", "from_state", "to_state")},
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("version", "code")},
        ),
    ]
