# Generated by Django 5.0.2 on 2026-05-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instancehistory",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="التوقيع الرقمي (لضمان عدم التلاعب)",
            ),
        ),
    ]
