version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: hrms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrms_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: hrms_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrms_network

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hrms_network


  # Celery Worker (المرحلة 4: مهام غير متزامنة)
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms_celery
    command: celery -A hrms worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hrms_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  hrms_network:
    driver: bridge
