# Generated by Django 5.0.2 on 2026-05-19 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0017_variabletype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="يُبنى تلقائياً: module.action.scope",
                        max_length=100,
                        unique=True,
                        verbose_name="الكود",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="مثل: users, personnel, services, reports, system",
                        max_length=50,
                        verbose_name="النظام الفرعي",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="مثل: view, create, edit, delete, approve, export",
                        max_length=50,
                        verbose_name="الفعل",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        default="all",
                        help_text="مثل: all, own, department, governorate",
                        max_length=50,
                        verbose_name="النطاق",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=200, verbose_name="الوصف بالعربي"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="شرح تفصيلي"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("page", "صفحة"),
                            ("component", "عنصر واجهة"),
                            ("action", "إجراء"),
                            ("data", "نطاق بيانات"),
                            ("field", "حقل"),
                        ],
                        default="action",
                        help_text="المستوى: صفحة، عنصر، إجراء، بيانات، حقل",
                        max_length=20,
                        verbose_name="تصنيف الصلاحية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "is_system",
                    models.BooleanField(
                        default=True,
                        help_text="الصلاحيات النظامية لا يمكن حذفها",
                        verbose_name="صلاحية نظامية",
                    ),
                ),
                (
                    "requires_dual_auth",
                    models.BooleanField(
                        default=False, verbose_name="تتطلب تفويض مزدوج"
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية",
                "verbose_name_plural": "الصلاحيات",
                "db_table": "authorization_permission",
                "ordering": ["module", "action", "scope"],
                "indexes": [
                    models.Index(
                        fields=["module"], name="authorizati_module_3133bf_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="authorizati_is_acti_f44508_idx"
                    ),
                    models.Index(
                        fields=["module", "action"],
                        name="authorizati_module_76852c_idx",
                    ),
                    models.Index(
                        fields=["category"], name="authorizati_categor_4ac1a1_idx"
                    ),
                    models.Index(fields=["code"], name="authorizati_code_8e568a_idx"),
                ],
                "unique_together": {("module", "action", "scope")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الدور"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="مثل: admin, service_head, data_entry",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز الداخلي",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="الأدوار النظامية لا يمكن حذفها",
                        verbose_name="دور نظامي",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="رقم أعلى = أولوية أعلى — لحل التعارضات",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authz_created_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
                "db_table": "authorization_role",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُنحت بواسطة",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="authorization.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="authorization.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية دور",
                "verbose_name_plural": "صلاحيات الأدوار",
                "db_table": "authorization_role_permission",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="authorization.RolePermission",
                to="authorization.permission",
                verbose_name="الصلاحيات",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "supervises_all_departments",
                    models.BooleanField(
                        default=False, verbose_name="يشرف على جميع الإدارات"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "الإنجليزية")],
                        default="ar",
                        max_length=5,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المدير"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_staff_profiles",
                        to="core.department",
                        verbose_name="الإدارة",
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_staff_profiles",
                        to="core.directorate",
                        verbose_name="الإدارة العامة",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_staff_profiles",
                        to="core.division",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_staff_profiles",
                        to="core.governorate",
                        verbose_name="المحافظة",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_users",
                        to="authorization.role",
                        verbose_name="الدور الأساسي",
                    ),
                ),
                (
                    "supervised_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="auth_supervisors",
                        to="core.department",
                        verbose_name="الإدارات المُشرف عليها",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_staff_profiles",
                        to="core.unit",
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authz_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف مستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
                "db_table": "authorization_user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإسناد"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="اتركه فارغاً لدور دائم",
                        null=True,
                        verbose_name="تنتهي في",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authz_role_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُسند بواسطة",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="authorization.role",
                        verbose_name="الدور",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور مستخدم",
                "verbose_name_plural": "أدوار المستخدمين",
                "db_table": "authorization_user_role",
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="authorizati_code_0b327f_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="authorizati_is_acti_12c7c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="authorizati_role_id_8f772b_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["department"], name="authorizati_departm_00b76e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["governorate"], name="authorizati_governo_50bd84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_active"], name="authorizati_user_id_1fa868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="authorizati_role_id_79d5dc_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="authorizati_expires_3c2e5e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_permission RENAME TO authorization_permission;",
                    reverse_sql="ALTER TABLE IF EXISTS authorization_permission RENAME TO core_permission;"
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE authorization_permission ADD COLUMN IF NOT EXISTS category VARCHAR(20) DEFAULT 'action' NOT NULL;
                    CREATE INDEX IF NOT EXISTS authorizati_module_3133bf_idx ON authorization_permission (module);
                    CREATE INDEX IF NOT EXISTS authorizati_is_acti_f44508_idx ON authorization_permission (is_active);
                    CREATE INDEX IF NOT EXISTS authorizati_module_76852c_idx ON authorization_permission (module, action);
                    CREATE INDEX IF NOT EXISTS authorizati_categor_4ac1a1_idx ON authorization_permission (category);
                    CREATE INDEX IF NOT EXISTS authorizati_code_8e568a_idx ON authorization_permission (code);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS authorizati_module_3133bf_idx;
                    DROP INDEX IF EXISTS authorizati_is_acti_f44508_idx;
                    DROP INDEX IF EXISTS authorizati_module_76852c_idx;
                    DROP INDEX IF EXISTS authorizati_categor_4ac1a1_idx;
                    DROP INDEX IF EXISTS authorizati_code_8e568a_idx;
                    ALTER TABLE authorization_permission DROP COLUMN IF EXISTS category;
                    """
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE IF EXISTS core_role RENAME TO authorization_role;
                    ALTER TABLE IF EXISTS authorization_role DROP COLUMN IF EXISTS permissions;
                    ALTER TABLE IF EXISTS authorization_role DROP COLUMN IF EXISTS visible_pages;
                    """,
                    reverse_sql="""
                    ALTER TABLE IF EXISTS authorization_role ADD COLUMN IF NOT EXISTS permissions JSONB DEFAULT '[]'::jsonb NOT NULL;
                    ALTER TABLE IF EXISTS authorization_role ADD COLUMN IF NOT EXISTS visible_pages JSONB DEFAULT '[]'::jsonb NOT NULL;
                    ALTER TABLE IF EXISTS authorization_role RENAME TO core_role;
                    """
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_role_permission RENAME TO authorization_role_permission;",
                    reverse_sql="ALTER TABLE IF EXISTS authorization_role_permission RENAME TO core_role_permission;"
                ),
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE IF EXISTS core_user_profile RENAME TO authorization_user_profile;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS can_override_lock;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS requires_two_factor;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS is_account_locked;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS failed_login_attempts;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS locked_until;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS last_login_ip;
                    ALTER TABLE authorization_user_profile DROP COLUMN IF EXISTS last_login_user_agent;
                    """,
                    reverse_sql="""
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS can_override_lock BOOLEAN DEFAULT FALSE NOT NULL;
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS requires_two_factor BOOLEAN DEFAULT FALSE NOT NULL;
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS is_account_locked BOOLEAN DEFAULT FALSE NOT NULL;
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0 NOT NULL;
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP WITH TIME ZONE;
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(39);
                    ALTER TABLE authorization_user_profile ADD COLUMN IF NOT EXISTS last_login_user_agent TEXT DEFAULT '' NOT NULL;
                    ALTER TABLE IF EXISTS authorization_user_profile RENAME TO core_user_profile;
                    """
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_user_role RENAME TO authorization_user_role;",
                    reverse_sql="ALTER TABLE IF EXISTS authorization_user_role RENAME TO core_user_role;"
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS core_userprofile_supervised_departments RENAME TO authorization_user_profile_supervised_departments;",
                    reverse_sql="ALTER TABLE IF EXISTS authorization_user_profile_supervised_departments RENAME TO core_userprofile_supervised_departments;"
                ),
            ]
        )
    ]
