# Generated by Django 5.0.2 on 2026-05-20 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
        ("core", "0019_remove_loginauditlog_user_delete_auditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="authorizati_departm_00b76e_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="supervised_departments",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="supervises_all_departments",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervised_directorates",
            field=models.ManyToManyField(
                blank=True,
                related_name="auth_supervisors",
                to="core.directorate",
                verbose_name="الإدارات العامة المُشرف عليها",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervises_all_directorates",
            field=models.BooleanField(
                default=False, verbose_name="يشرف على جميع الإدارات العامة"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["directorate"], name="authorizati_directo_cc8683_idx"
            ),
        ),
    ]
