# Generated by Django 5.0.2 on 2026-05-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_seed_permissions_and_roles"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="authorizati_governo_50bd84_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="authorizati_directo_cc8683_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="governorate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="supervised_directorates",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="supervises_all_directorates",
        ),
    ]
