# Generated by Django 5.0.2 on 2026-05-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization",
            "0004_remove_userprofile_authorizati_governo_50bd84_idx_and_more",
        ),
        ("core", "0022_branch_centraldepartment_districtpolice_geodistrict_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_staff_profiles",
                to="core.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="central_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_staff_profiles",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_staff_profiles",
                to="core.districtpolice",
                verbose_name="أمن المديرية",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="security_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_staff_profiles",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervised_security_admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="auth_supervisors",
                to="core.securityadministration",
                verbose_name="إدارات الأمن المُشرف عليها",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervises_all",
            field=models.BooleanField(
                default=False, verbose_name="يشرف على جميع الإدارات"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["security_admin"], name="authorizati_securit_dcbdee_idx"
            ),
        ),
    ]
