# Generated by Django 5.2.15 on 2026-06-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_create_missing_roles"),
        (
            "authorization",
            "0005_userprofile_branch_userprofile_central_department_and_more",
        ),
    ]

    operations = []
