# Generated by Django 5.0.2 on 2026-06-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_merge_20260624_1156"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["-priority", "name"],
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
            },
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "verbose_name": "صلاحية مجموعة",
                "verbose_name_plural": "صلاحيات المجموعات",
            },
        ),
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                help_text="مثل: users, personnel, services, reports, system",
                max_length=50,
                verbose_name="الشاشة",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False,
                help_text="المجموعات النظامية لا يمكن حذفها",
                verbose_name="مجموعة نظامية",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="اسم المجموعة"
            ),
        ),
    ]
