# Generated by Django 5.2.15 on 2026-07-04 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization",
            "0007_alter_role_options_alter_rolepermission_options_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="مثل: users, personnel, reports, security",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثل: المستخدمين، شؤون الأفراد",
                        max_length=100,
                        verbose_name="الاسم بالعربي",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "icon",
                    models.CharField(
                        default="shield",
                        help_text="اسم الأيقونة للـ Frontend: users, shield, file-text",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="رقم أقل = يظهر أولاً",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
            ],
            options={
                "verbose_name": "مجموعة صلاحيات",
                "verbose_name_plural": "مجموعات الصلاحيات",
                "db_table": "authorization_permission_group",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="مثل: personnel, services, finance",
                        max_length=50,
                        verbose_name="النظام الفرعي",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="اسم الحقل في الـ Serializer: salary, bank_account, military_number",
                        max_length=100,
                        verbose_name="اسم الحقل",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="مثل: الراتب، الحساب البنكي",
                        max_length=200,
                        verbose_name="الوصف بالعربي",
                    ),
                ),
                (
                    "view_permission",
                    models.CharField(
                        help_text="كود الصلاحية المطلوبة للعرض: personnel.view_salary.all",
                        max_length=100,
                        verbose_name="صلاحية العرض",
                    ),
                ),
                (
                    "edit_permission",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="كود الصلاحية المطلوبة للتعديل: personnel.edit_salary.all",
                        max_length=100,
                        verbose_name="صلاحية التعديل",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=True,
                        help_text="الحقول الحساسة يُسجّل الوصول إليها في سجل التدقيق",
                        verbose_name="حقل حساس",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "صلاحية حقل",
                "verbose_name_plural": "صلاحيات الحقول",
                "db_table": "authorization_field_permission",
                "ordering": ["module", "field_name"],
                "indexes": [
                    models.Index(
                        fields=["module"], name="authorizati_module_80143d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="authorizati_is_acti_0ae18e_idx"
                    ),
                ],
                "unique_together": {("module", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="AccessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم السياسة")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="رمز فريد للسياسة",
                        max_length=100,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "permission_code",
                    models.CharField(
                        help_text="كود الصلاحية التي تُطبَّق عليها: personnel.edit.all",
                        max_length=100,
                        verbose_name="الصلاحية المستهدفة",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اسم النموذج: PersonnelMaster, Document (فارغ = كل النماذج)",
                        max_length=100,
                        verbose_name="النموذج المستهدف",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text='قائمة شروط JSON. كل شرط: {"field": "user.branch_id", "op": "eq", "value_ref": "obj.branch_id"}',
                        verbose_name="الشروط",
                    ),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "سماح"), ("deny", "منع")],
                        default="allow",
                        max_length=10,
                        verbose_name="التأثير",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="رقم أعلى = أولوية أعلى — يُنفَّذ أولاً",
                        verbose_name="الأولوية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشئت بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سياسة وصول",
                "verbose_name_plural": "سياسات الوصول",
                "db_table": "authorization_access_policy",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["permission_code", "is_active"],
                        name="authorizati_permiss_39f258_idx",
                    ),
                    models.Index(
                        fields=["-priority"], name="authorizati_priorit_73b861_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="authorizati_model_n_202a86_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("reason", models.TextField(verbose_name="سبب التفويض")),
                ("starts_at", models.DateTimeField(verbose_name="يبدأ من")),
                ("ends_at", models.DateTimeField(verbose_name="ينتهي في")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("expired", "منتهي"),
                            ("revoked", "ملغي"),
                            ("pending", "قيد الانتظار"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإلغاء"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="فارغ = تفويض ذاتي لا يحتاج موافقة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="وافق عليه",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        help_text="المستخدم الذي يستلم الصلاحيات",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُفوَّض إليه",
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        help_text="المستخدم الذي يمنح صلاحياته",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُفوِّض",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اتركها فارغة إذا تم تحديد دور — ستُفوَّض كل صلاحيات الدور",
                        related_name="delegations",
                        to="authorization.permission",
                        verbose_name="صلاحيات محددة",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegation_revocations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ألغاه",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="اتركه فارغاً لتفويض صلاحيات محددة بدلاً من دور كامل",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="authorization.role",
                        verbose_name="الدور المُفوَّض",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفويض",
                "verbose_name_plural": "التفويضات",
                "db_table": "authorization_delegation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delegator", "status"],
                        name="authorizati_delegat_8993d7_idx",
                    ),
                    models.Index(
                        fields=["delegate", "status"],
                        name="authorizati_delegat_a2fb97_idx",
                    ),
                    models.Index(
                        fields=["status", "starts_at", "ends_at"],
                        name="authorizati_status_9cc146_idx",
                    ),
                    models.Index(
                        fields=["ends_at"], name="authorizati_ends_at_412e8a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="إلزامي — يُعرض في التدقيق", verbose_name="سبب الطوارئ"
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ المنح"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="أقصى مدة: 24 ساعة", verbose_name="ينتهي في"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("expired", "منتهي"),
                            ("revoked", "ملغي"),
                            ("reviewed", "تمت المراجعة"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإلغاء"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "audit_notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات المراجع بعد انتهاء الطوارئ",
                        verbose_name="ملاحظات التدقيق",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُنح بواسطة",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        related_name="emergency_accesses",
                        to="authorization.permission",
                        verbose_name="الصلاحيات الممنوحة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_revocations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ألغاه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "وصول طارئ",
                "verbose_name_plural": "وصول الطوارئ",
                "db_table": "authorization_emergency_access",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="authorizati_user_id_58168f_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="authorizati_status_2d3cb5_idx",
                    ),
                    models.Index(
                        fields=["granted_by"], name="authorizati_granted_23f872_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecordACL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="معرف السجل"),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("allow", "سماح"), ("deny", "منع")],
                        default="deny",
                        max_length=10,
                        verbose_name="نوع القيد",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اتركه فارغاً لتقييد كل العمليات على هذا السجل",
                        max_length=100,
                        verbose_name="الصلاحية المقيّدة",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب القيد")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="اتركه فارغاً لقيد دائم",
                        null=True,
                        verbose_name="تنتهي في",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="مثل: PersonnelMaster, Document",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="نوع السجل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_record_acls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُنشئ بواسطة",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="اتركه فارغاً لعدم تقييد دور",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_acls",
                        to="authorization.role",
                        verbose_name="الدور",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="اتركه فارغاً لتطبيق القيد على الجميع",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_acls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد وصول سجل",
                "verbose_name_plural": "قيود الوصول على السجلات",
                "db_table": "authorization_record_acl",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="authorizati_content_3f819c_idx",
                    ),
                    models.Index(
                        fields=["target_user", "is_active"],
                        name="authorizati_target__bf59f5_idx",
                    ),
                    models.Index(
                        fields=["target_role", "is_active"],
                        name="authorizati_target__b23ffc_idx",
                    ),
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="authorizati_is_acti_c6b8ec_idx",
                    ),
                ],
            },
        ),
    ]
