# Generated by Django 5.2.15 on 2026-07-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_add_delegation_emergency_policy_fieldperm_recordacl"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="يُحدد تلقائياً بواسطة seed_permissions حسب الوحدة (module)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="authorization.permissiongroup",
                verbose_name="مجموعة الصلاحيات",
            ),
        ),
    ]
