# Generated by Django 5.0.2 on 2026-05-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
        ("workflows", "0002_instancehistory_signature_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="required_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="authorization.role",
                verbose_name="الدور المطلوب",
            ),
        ),
        migrations.AlterField(
            model_name="escalationrule",
            name="escalate_to_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="authorization.role",
                verbose_name="الدور المُصعّد إليه",
            ),
        ),
    ]
