# Generated by Django 5.0.2 on 2026-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_mv_personnel_snapshot"),
        ("security", "0005_userprofile_directorate_userprofile_division_and_more"),
    ]

    operations = []
