# Generated by Django 5.0.2 on 2026-05-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0008_remove_dualauthorizationrequest_created_at_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="UserSession",
                ),
            ],
            database_operations=[]
        )
    ]
