# Generated by Django 5.0.2 on 2026-05-16 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0015_remove_document_personnel_remove_document_temp_owner_and_more"),
        ("personnel", "0014_add_corrected_name_and_name_validators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id_front", "بطاقة وطنية - أمامي"),
                            ("national_id_back", "بطاقة وطنية - خلفي"),
                            ("national_id_scan", "بطاقة وطنية - ماسح ضوئي"),
                            ("military_id_front", "بطاقة عسكرية - أمامي"),
                            ("military_id_back", "بطاقة عسكرية - خلفي"),
                            ("rank_decision", "قرار ترقية"),
                            ("settlement_decision", "قرار تسوية فرد→ضابط"),
                            ("transfer_order", "أمر نقل"),
                            ("name_correction_order", "قرار تصحيح اسم"),
                            ("status_change_order", "قرار تغيير حالة خدمية"),
                            ("leave_request", "طلب إجازة"),
                            ("medical_report", "تقرير طبي"),
                            ("sick_leave", "إجازة مرضية"),
                            ("memo", "مذكرة"),
                            ("letter", "خطاب رسمي"),
                            ("certificate", "شهادة"),
                            ("personal_photo", "صورة شخصية"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        help_text="تصنيف المرفق — بطاقة وطنية، قرار ترقية، إلخ",
                        max_length=30,
                        verbose_name="نوع المرفق",
                    ),
                ),
                (
                    "related_field",
                    models.CharField(
                        blank=True,
                        help_text="اسم الحقل الذي يخص هذا المرفق — مثل: national_id, military_number, current_rank, current_status, full_name",
                        max_length=50,
                        null=True,
                        verbose_name="الحقل المرتبط",
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        blank=True,
                        help_text="نوع الكيان المرتبط — مثل: SuggestedCorrection, RankSettlement, ServiceEventLog",
                        max_length=50,
                        null=True,
                        verbose_name="نوع السياق",
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        blank=True,
                        help_text="المعرف الفريد للكيان المرتبط",
                        max_length=50,
                        null=True,
                        verbose_name="معرف السياق",
                    ),
                ),
                (
                    "source_method",
                    models.CharField(
                        choices=[
                            ("upload", "رفع من الكمبيوتر"),
                            ("scanner", "ماسح ضوئي"),
                            ("camera", "كاميرا / هاتف"),
                        ],
                        default="upload",
                        max_length=10,
                        verbose_name="طريقة الرفع",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="الملف"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="Hash"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="الإصدار")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("temp", "مؤقت"),
                            ("committed", "مثبت"),
                            ("archived", "مؤرشف"),
                        ],
                        default="committed",
                        max_length=20,
                        verbose_name="حالة الملف",
                    ),
                ),
                (
                    "temp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تنتهي صلاحية المؤقت في"
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
                (
                    "temp_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temp_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مالك الملف المؤقت",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق",
                "verbose_name_plural": "المرفقات",
                "db_table": "services_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="services_do_status_af5c5b_idx"
                    ),
                    models.Index(
                        fields=["document_type"], name="services_do_documen_993f49_idx"
                    ),
                    models.Index(
                        fields=["related_field"], name="services_do_related_a9221c_idx"
                    ),
                    models.Index(
                        fields=["context_type", "context_id"],
                        name="services_do_context_f4a698_idx",
                    ),
                    models.Index(
                        fields=["personnel", "document_type"],
                        name="services_do_personn_6d70e7_idx",
                    ),
                ],
            },
        ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE services_document ADD COLUMN IF NOT EXISTS personnel_id VARCHAR(7) NULL REFERENCES personnel_master(military_number) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE services_document ADD COLUMN IF NOT EXISTS temp_owner_id INTEGER NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE services_document ADD COLUMN IF NOT EXISTS uploaded_by_id INTEGER NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql="""
                    ALTER TABLE services_document DROP COLUMN IF EXISTS personnel_id;
                    ALTER TABLE services_document DROP COLUMN IF EXISTS temp_owner_id;
                    ALTER TABLE services_document DROP COLUMN IF EXISTS uploaded_by_id;
                    """
                ),
            ],
        ),
    ]
