# Generated by Django 5.0.2 on 2026-05-23 13:13

import infra.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=infra.storage.models.Document._get_document_type_choices,
                default="other",
                help_text="تصنيف المرفق — بطاقة وطنية، قرار ترقية، إلخ",
                max_length=30,
                verbose_name="نوع المرفق",
            ),
        ),
    ]
