# Generated by Django 5.0.2 on 2026-07-06 12:15

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_securityadministration_geo_governorate"),
        ("personnel", "0033_alter_suggestedcorrection_correction_type"),
        ("secretariat", "0002_correspondenceattachment_documentworkrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="رمز الباركود الورقي",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="confidentiality_level",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("confidential", "سري"),
                    ("very_confidential", "سري للغاية"),
                    ("top_secret", "سري جداً"),
                ],
                default="normal",
                max_length=30,
                verbose_name="درجة السرية",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="parent_correspondence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="secretariat.correspondence",
                verbose_name="رد على المراسلة",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="tracking_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name="رمز التتبع"
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="urgency_level",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("urgent", "عاجل"),
                    ("very_urgent", "عاجل جداً"),
                    ("immediate", "فوري"),
                ],
                default="normal",
                max_length=30,
                verbose_name="درجة الاستعجال",
            ),
        ),
        migrations.AddField(
            model_name="historicalcorrespondence",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="رمز الباركود الورقي",
            ),
        ),
        migrations.AddField(
            model_name="historicalcorrespondence",
            name="confidentiality_level",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("confidential", "سري"),
                    ("very_confidential", "سري للغاية"),
                    ("top_secret", "سري جداً"),
                ],
                default="normal",
                max_length=30,
                verbose_name="درجة السرية",
            ),
        ),
        migrations.AddField(
            model_name="historicalcorrespondence",
            name="parent_correspondence",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="secretariat.correspondence",
                verbose_name="رد على المراسلة",
            ),
        ),
        migrations.AddField(
            model_name="historicalcorrespondence",
            name="tracking_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name="رمز التتبع"
            ),
        ),
        migrations.AddField(
            model_name="historicalcorrespondence",
            name="urgency_level",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("urgent", "عاجل"),
                    ("very_urgent", "عاجل جداً"),
                    ("immediate", "فوري"),
                ],
                default="normal",
                max_length=30,
                verbose_name="درجة الاستعجال",
            ),
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="minimum_stock_level",
            field=models.PositiveIntegerField(
                default=5, verbose_name="حد الطلب الأدنى"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="minimum_stock_level",
            field=models.PositiveIntegerField(
                default=5, verbose_name="حد الطلب الأدنى"
            ),
        ),
        migrations.CreateModel(
            name="CorrespondenceReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(verbose_name="التوجيه / الشرح المكتوب"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإحالة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("read", "مقروءة"),
                            ("completed", "تم الإجراء"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="رد الموظف/ملاحظات العمل"
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="secretariat.correspondence",
                        verbose_name="المراسلة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُحيل",
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_referrals",
                        to="personnel.personnelmaster",
                        verbose_name="المُحال إليه",
                    ),
                ),
                (
                    "security_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.securityadministration",
                        verbose_name="إدارة الأمن",
                    ),
                ),
            ],
            options={
                "verbose_name": "إحالة مراسلة",
                "verbose_name_plural": "إحالات المراسلات",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCorrespondenceReferral",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ التحديث"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(verbose_name="التوجيه / الشرح المكتوب"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ الإحالة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("read", "مقروءة"),
                            ("completed", "تم الإجراء"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="رد الموظف/ملاحظات العمل"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="secretariat.correspondence",
                        verbose_name="المراسلة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُحيل",
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.personnelmaster",
                        verbose_name="المُحال إليه",
                    ),
                ),
                (
                    "security_admin",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.securityadministration",
                        verbose_name="إدارة الأمن",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical إحالة مراسلة",
                "verbose_name_plural": "historical إحالات المراسلات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
