# Generated by Django 5.0.2 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretariat", "0003_correspondence_barcode_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="رد الموظف/ملاحظات العمل"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="رد الموظف/ملاحظات العمل"
            ),
        ),
    ]
