# Generated by Django 5.0.2 on 2026-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mime_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="نوع الملف (MIME)"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="اسم الملف الأصلي"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="حجم الملف"
            ),
        ),
    ]
