# Generated by Django 5.0.2 on 2026-05-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_document_mime_type_document_original_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id_front", "بطاقة وطنية - أمامي"),
                    ("national_id_back", "بطاقة وطنية - خلفي"),
                    ("national_id_scan", "بطاقة وطنية - ماسح ضوئي"),
                    ("military_id_front", "بطاقة عسكرية - أمامي"),
                    ("military_id_back", "بطاقة عسكرية - خلفي"),
                    ("rank_decision", "قرار ترقية"),
                    ("settlement_decision", "قرار تسوية فرد→ضابط"),
                    ("transfer_order", "أمر نقل"),
                    ("name_correction_order", "قرار تصحيح اسم"),
                    ("status_change_order", "قرار تغيير حالة خدمية"),
                    ("leave_request", "طلب إجازة"),
                    ("medical_report", "قرار طبي أصل / تقرير طبي"),
                    ("sick_leave", "إجازة مرضية"),
                    ("death_cert", "شهادة وفاة"),
                    ("inheritance_ruling", "حكم انحصار الورثة"),
                    ("legal_power_of_attorney", "وكالة شرعية"),
                    ("installation_ruling", "حكم تنصيب"),
                    ("court_ruling_missing", "حكم شرعي بالفقدان"),
                    ("newspaper_announcement", "إعلان الجريدة الرسمية"),
                    ("missing_report", "بلاغ الفقدان"),
                    ("incident_report", "بلاغ العمليات"),
                    ("martyr_form", "استمارة استشهاد"),
                    ("personal_request", "طلب شخصي"),
                    ("agent_id_copy", "صورة البطاقة الشخصية للوكيل"),
                    ("patient_photo", "صورة حديثة للمريض"),
                    ("court_verdict", "نسخة من الحكم"),
                    ("prison_memo", "مذكرة نيابة (استمرار السجن)"),
                    ("assignment_order", "نسخة الأمر / تكليف مهمة"),
                    ("study_leave_order", "أمر تفرغ دراسي"),
                    ("secondment_order", "أمر انتداب"),
                    ("memo", "مذكرة عودة / إرسال"),
                    ("letter", "خطاب رسمي"),
                    ("certificate", "شهادة"),
                    ("personal_photo", "صورة شخصية"),
                    ("other", "أخرى"),
                ],
                default="other",
                help_text="تصنيف المرفق — بطاقة وطنية، قرار ترقية، إلخ",
                max_length=30,
                verbose_name="نوع المرفق",
            ),
        ),
    ]
