# Generated by Django 5.0.2 on 2026-05-19 19:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="الاسم الرباعي أو الكامل للمستخدم",
                        max_length=300,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "db_table": "accounts_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="محاولات الدخول الفاشلة"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="يُقفل تلقائياً بعد 5 محاولات فاشلة",
                        verbose_name="مقفل",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مقفل حتى"
                    ),
                ),
                (
                    "last_failed_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آخر IP فاشل"
                    ),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر محاولة فاشلة"
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تغيير كلمة مرور"
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="يُفعّل عند إعادة تعيين كلمة المرور بواسطة المدير",
                        verbose_name="يجب تغيير كلمة المرور",
                    ),
                ),
                (
                    "password_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="هاشات آخر 5 كلمات مرور لمنع إعادة الاستخدام",
                        verbose_name="سجل كلمات المرور",
                    ),
                ),
                (
                    "last_known_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="آخر IP ناجح — للكشف عن تغيير الموقع",
                        null=True,
                        verbose_name="آخر IP معروف",
                    ),
                ),
                (
                    "last_known_user_agent",
                    models.TextField(
                        blank=True, default="", verbose_name="آخر User Agent معروف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف أمان",
                "verbose_name_plural": "ملفات الأمان",
                "db_table": "accounts_security_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="المعرف",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="يُضمّن في Access Token كـ claim",
                        unique=True,
                        verbose_name="معرف الجلسة",
                    ),
                ),
                (
                    "refresh_token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash — لا نخزّن التوكن الأصلي أبداً",
                        max_length=128,
                        verbose_name="هاش Refresh Token",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثل: iPhone 15, Windows PC",
                        max_length=200,
                        verbose_name="اسم الجهاز",
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثل: Chrome 120, Safari 17",
                        max_length=200,
                        verbose_name="المتصفح",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثل: Windows 11, iOS 17, Android 14",
                        max_length=200,
                        verbose_name="نظام التشغيل",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="يُحدَّث مع كل طلب عبر Middleware",
                        verbose_name="آخر نشاط",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="بعد هذا التاريخ الجلسة غير صالحة",
                        verbose_name="تنتهي في",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="إذا تم إلغاؤها يدوياً أو بسبب خمول",
                        null=True,
                        verbose_name="ألغيت في",
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثل: manual, inactivity, logout, security",
                        max_length=50,
                        verbose_name="سبب الإلغاء",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة مستخدم",
                "verbose_name_plural": "جلسات المستخدمين",
                "db_table": "accounts_user_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="accounts_us_usernam_c0ea66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4734df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityprofile",
            index=models.Index(
                fields=["is_locked"], name="accounts_se_is_lock_f69818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityprofile",
            index=models.Index(
                fields=["last_failed_at"], name="accounts_se_last_fa_50d8c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_us_user_id_f3bc3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token_hash"], name="accounts_us_refresh_75b3ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="accounts_us_last_ac_394558_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="accounts_us_expires_89e160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="accounts_us_is_acti_ecc110_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.CheckConstraint(
                check=models.Q(("expires_at__gt", models.F("created_at"))),
                name="session_expires_after_creation",
            ),
        ),
    ]
