# Generated by Django 5.0.2 on 2026-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, default="", verbose_name="النبذة التعريفية"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_link",
            field=models.URLField(blank=True, default="", verbose_name="رابط فيسبوك"),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_link",
            field=models.URLField(blank=True, default="", verbose_name="رابط إنستجرام"),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_link",
            field=models.URLField(blank=True, default="", verbose_name="رابط لينكد إن"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profiles/",
                verbose_name="الصورة الشخصية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="x_link",
            field=models.URLField(blank=True, default="", verbose_name="رابط إكس"),
        ),
    ]
