# Generated by Django 5.0.2 on 2026-07-08 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, verbose_name='معرف التقرير')),
                ('report_name', models.CharField(max_length=255, verbose_name='اسم التقرير')),
                ('reason', models.TextField(verbose_name='سبب التصدير')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exports', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب تصدير',
                'verbose_name_plural': 'طلبات التصدير',
                'ordering': ['-created_at'],
            },
        ),
    ]
