# Generated by Django 5.0.2 on 2026-07-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLayoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="الرمز (Slug)"
                    ),
                ),
                (
                    "header_columns",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="أعمدة الترويسة"
                    ),
                ),
                (
                    "header_blocks",
                    models.JSONField(
                        default=list,
                        help_text="مصفوفة من النصوص (HTML) لكل عمود",
                        verbose_name="محتوى الترويسة",
                    ),
                ),
                (
                    "footer_columns",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="أعمدة التذييل"
                    ),
                ),
                (
                    "footer_blocks",
                    models.JSONField(
                        default=list,
                        help_text="مصفوفة من النصوص (HTML) لكل عمود",
                        verbose_name="محتوى التذييل",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_layout_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخطيط قالب التقرير",
                "verbose_name_plural": "تخطيط قوالب التقارير",
                "db_table": "reports_report_layout_template",
                "ordering": ["name"],
            },
        ),
    ]
