# Generated by Django 5.0.2 on 2026-04-02 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_alter_department_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("login_failures", "محاولات دخول فاشلة"),
                            ("active_sessions", "جلسات نشطة"),
                            ("pending_dual_auth", "طلبات تفويض معلقة"),
                            ("shadow_table_sizes", "أحجام جداول الظل"),
                            ("atomic_transactions", "إحصائيات المعاملات الذرية"),
                            ("slow_queries", "أبطأ الاستعلامات"),
                            ("audit_integrity", "سلامة سجل التدقيق"),
                            ("system_health", "صحة النظام العامة"),
                        ],
                        max_length=30,
                        verbose_name="نوع المقياس",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="بيانات المقياس بتنسيق JSON", verbose_name="البيانات"
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التجميع"
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة إحصائيات",
                "verbose_name_plural": "لقطات الإحصائيات",
                "db_table": "security_metrics_snapshot",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "collected_at"],
                        name="security_me_metric__13384d_idx",
                    ),
                    models.Index(
                        fields=["collected_at"], name="security_me_collect_390162_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الدور"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثل: super_admin, services_chief, inspector",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز الداخلي",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="الأدوار النظامية لا يمكن حذفها",
                        verbose_name="دور نظامي",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="قائمة رموز الصلاحيات المسموحة",
                        verbose_name="الصلاحيات",
                    ),
                ),
                (
                    "visible_pages",
                    models.JSONField(
                        default=list,
                        help_text="قائمة مسارات الصفحات المرئية للمستخدم",
                        verbose_name="الصفحات المسموحة",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="رقم أعلى = صلاحيات أعلى. super_admin = 100",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دور",
                "verbose_name_plural": "الأدوار",
                "db_table": "security_role",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.JSONField(verbose_name="القيمة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("security", "الأمان"),
                            ("import_export", "التصدير والاستيراد"),
                            ("notifications", "الإشعارات"),
                            ("performance", "الأداء"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="الإعدادات الحساسة تتطلب تفويض مزدوج للتعديل",
                        verbose_name="حساس",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عُدّل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "db_table": "security_system_setting",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "supervises_all_departments",
                    models.BooleanField(
                        default=False, verbose_name="يشرف على جميع الإدارات"
                    ),
                ),
                (
                    "can_override_lock",
                    models.BooleanField(
                        default=False,
                        help_text="لمدير النظام فقط",
                        verbose_name="صلاحية إلغاء الإقفال",
                    ),
                ),
                (
                    "requires_two_factor",
                    models.BooleanField(default=False, verbose_name="يتطلب تحقق ثنائي"),
                ),
                (
                    "is_account_locked",
                    models.BooleanField(
                        default=False,
                        help_text="يتم قفل الحساب بعد 5 محاولات دخول فاشلة",
                        verbose_name="حساب مغلق",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, verbose_name="محاولات دخول فاشلة"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مقفل حتى"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آخر IP"
                    ),
                ),
                (
                    "last_login_user_agent",
                    models.TextField(blank=True, verbose_name="آخر User Agent"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "الإنجليزية")],
                        default="ar",
                        max_length=5,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المدير"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="إدارة المستخدم (للمستخدم العادي ومسؤول الإدارة)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profiles",
                        to="core.department",
                        verbose_name="الإدارة",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="security.role",
                        verbose_name="الدور",
                    ),
                ),
                (
                    "supervised_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="لرئيس الخدمات: الإدارات التي يشرف عليها",
                        related_name="supervisors",
                        to="core.department",
                        verbose_name="الإدارات المُشرف عليها",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف مستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
                "db_table": "security_user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="بدأت في"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة مستخدم",
                "verbose_name_plural": "جلسات المستخدمين",
                "db_table": "security_user_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="DualAuthorizationRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DELETE_PERSONNEL", "حذف فرد نهائياً"),
                            ("UNLOCK_MONTH", "إلغاء إقفال شهر"),
                            ("MODIFY_SUPER_ADMIN", "تعديل صلاحيات مدير النظام"),
                            ("CHANGE_ENCRYPTION_KEY", "تغيير مفتاح التشفير"),
                            ("BULK_DELETE", "حذف جماعي"),
                            ("RESTORE_BACKUP", "استعادة نسخة احتياطية"),
                        ],
                        max_length=30,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        help_text="مثل: PersonnelMaster, MonthlySnapshot, User",
                        max_length=100,
                        verbose_name="نوع الكائن المستهدف",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        max_length=100, verbose_name="معرف الكائن المستهدف"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        default=dict,
                        help_text="تفاصيل العملية المطلوبة (سبب، تفاصيل)",
                        verbose_name="بيانات الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "موافق عليه"),
                            ("rejected", "مرفوض"),
                            ("expired", "منتهي الصلاحية"),
                            ("cancelled", "ملغي"),
                            ("executed", "تم التنفيذ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="ينتهي الطلب تلقائياً بعد 7 أيام",
                        verbose_name="تنتهي في",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التنفيذ"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "execution_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="نتيجة التنفيذ"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dual_auth_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموافق",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dual_auth_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تفويض مزدوج",
                "verbose_name_plural": "طلبات التفويض المزدوج",
                "db_table": "security_dual_auth_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="security_du_status_a421d4_idx"
                    ),
                    models.Index(
                        fields=["action_type", "status"],
                        name="security_du_action__0bbf78_idx",
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="security_du_request_66719d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="security_du_expires_f3f21d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="security_ro_code_c60f83_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="security_ro_is_acti_d4ad46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(
                fields=["category"], name="security_sy_categor_0158e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="security_us_role_id_9de83d_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["department"], name="security_us_departm_0abf12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["is_account_locked"], name="security_us_is_acco_cb1490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="security_us_user_id_c68a39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="security_us_last_ac_db19a3_idx"
            ),
        ),
    ]
