# Generated by Django 5.0.2 on 2026-04-02 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_default_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, verbose_name="مفتاح Idempotency"),
                ),
                ("status_code", models.IntegerField(verbose_name="كود الاستجابة")),
                ("response_data", models.JSONField(verbose_name="بيانات الاستجابة")),
                (
                    "endpoint",
                    models.CharField(max_length=255, verbose_name="نقطة النهاية"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تنتهي في")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل Idempotency",
                "verbose_name_plural": "سجلات Idempotency",
                "db_table": "security_idempotency_record",
                "indexes": [
                    models.Index(
                        fields=["key", "user"], name="security_id_key_7d234f_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="security_id_expires_a09641_idx"
                    ),
                ],
                "unique_together": {("key", "user")},
            },
        ),
    ]
