# Generated by Django 5.0.2 on 2026-04-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_directorate_governorate_division_and_more"),
        ("security", "0004_idempotencyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.directorate",
                verbose_name="الإدارة العامة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.division",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                help_text="المحافظة التابع لها المستخدم (فارغ للمدير العام)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="core.unit",
                verbose_name="الوحدة",
            ),
        ),
    ]
