# Generated by Django 5.0.2 on 2026-05-16 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0007_remove_role_userprofile_to_core"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dualauthorizationrequest",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dualauthorizationrequest",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="dualauthorizationrequest",
            name="expires_at",
            field=models.DateTimeField(verbose_name="تنتهي في"),
        ),
        migrations.AlterField(
            model_name="dualauthorizationrequest",
            name="request_data",
            field=models.JSONField(default=dict, verbose_name="بيانات الطلب"),
        ),
        migrations.AlterField(
            model_name="dualauthorizationrequest",
            name="target_object_type",
            field=models.CharField(max_length=100, verbose_name="نوع الكائن المستهدف"),
        ),
        migrations.AlterField(
            model_name="metricssnapshot",
            name="data",
            field=models.JSONField(verbose_name="البيانات"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="is_sensitive",
            field=models.BooleanField(default=False, verbose_name="حساس"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
