# Generated by Django 5.0.2 on 2026-04-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_department_options_and_more"),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="data_quality_score",
            field=models.IntegerField(default=0, verbose_name="درجة جودة البيانات"),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="is_data_clean",
            field=models.BooleanField(default=False, verbose_name="بيانات نظيفة"),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="is_temporary",
            field=models.BooleanField(default=False, verbose_name="رقم عسكري مؤقت"),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="national_id_duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="personnel.personnelmaster",
                verbose_name="مكرر من",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="national_id_status",
            field=models.CharField(
                choices=[
                    ("valid", "صحيح"),
                    ("missing", "ناقص"),
                    ("duplicate", "مكرر"),
                    ("under_review", "تحت المراجعة"),
                    ("invalid_length", "طول غير صحيح"),
                ],
                default="valid",
                max_length=20,
                verbose_name="حالة الرقم الوطني",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات"),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="pending_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_personnel",
                to="core.rank",
                verbose_name="الرتبة المعلقة",
            ),
        ),
    ]
