# Generated by Django 5.0.2 on 2026-04-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_directorate_governorate_division_and_more"),
        ("personnel", "0003_rawdataimport_suggestedcorrection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.directorate",
                verbose_name="الإدارة العامة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.division",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="governorate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personnel",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.unit",
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="current_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_personnel",
                to="core.department",
                verbose_name="الإدارة الحالية (هيكل قديم)",
            ),
        ),
    ]
