# Generated by Django 5.0.2 on 2026-04-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_directorate_governorate_division_and_more"),
        (
            "personnel",
            "0004_personnelmaster_directorate_personnelmaster_division_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedcorrection",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggested_corrections",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
    ]
