# Generated by Django 5.0.2 on 2026-05-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_statetransitionrule_and_more"),
        ("personnel", "0006_personnel_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.jobcategory",
                verbose_name="الفئة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="force_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.forcetype",
                verbose_name="تصنيف القوة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.jobtitle",
                verbose_name="نوع العمل",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.position",
                verbose_name="المنصب",
            ),
        ),
    ]
