# Generated by Django 5.0.2 on 2026-05-02 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_directorate_node_type_position_allowed_categories_and_more"),
        ("personnel", "0008_add_chk_min_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="appointment_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="معلومات التعيين"
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="decision_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ صدور القرار"
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="expense_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("has_expenses", "لديه نفقات"),
                    ("no_expenses", "بدون نفقات"),
                    ("expenses", "نفقات"),
                ],
                max_length=30,
                null=True,
                verbose_name="حالة النفقات",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="officer_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="رقم الضابط"
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="transfer_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ التصدور إلينا"
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="join_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الالتحاق"
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="الرقم الوطني",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personnel",
                to="core.qualification",
                verbose_name="المؤهل الدراسي",
            ),
        ),
    ]
