# Generated by Django 5.0.2 on 2026-05-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0017_alter_historicalmonthlyvariables_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="is_temporary",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="is_temporary",
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION calculate_data_quality_score()
            RETURNS TRIGGER AS $$
            DECLARE
                score INTEGER := 0;
            BEGIN
                -- الحقول الإلزامية (10 نقاط لكل حقل)
                IF NEW.military_number IS NOT NULL AND LENGTH(NEW.military_number) = 7 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.national_id IS NOT NULL AND LENGTH(NEW.national_id) = 11 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.full_name IS NOT NULL AND LENGTH(TRIM(NEW.full_name)) > 0 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.birth_date IS NOT NULL THEN
                    score := score + 10;
                END IF;
                
                IF NEW.join_date IS NOT NULL THEN
                    score := score + 10;
                END IF;
                
                -- الحقول الاختيارية (5 نقاط لكل حقل)
                IF NEW.phone_number IS NOT NULL AND TRIM(NEW.phone_number) != '' THEN
                    score := score + 5;
                END IF;
                
                IF NEW.photo IS NOT NULL AND TRIM(NEW.photo) != '' THEN
                    score := score + 10;
                END IF;
                
                IF NEW.fingerprint_hash IS NOT NULL AND TRIM(NEW.fingerprint_hash) != '' THEN
                    score := score + 10;
                END IF;
                
                IF NEW.qualification_id IS NOT NULL THEN
                    score := score + 5;
                END IF;
                
                IF NEW.location_id IS NOT NULL THEN
                    score := score + 5;
                END IF;
                
                -- خصم نقاط للمشاكل (تم حذف فحص is_temporary وحساب حالة الرقم الوطني بالـ SQL)
                IF NEW.national_id IS NULL OR TRIM(NEW.national_id) = '' THEN
                    score := score - 15;
                ELSIF LENGTH(NEW.national_id) != 11 OR NEW.national_id !~ '^[0-9]+$' THEN
                    score := score - 15;
                ELSIF EXISTS (SELECT 1 FROM personnel_master WHERE national_id = NEW.national_id AND military_number != NEW.military_number) THEN
                    score := score - 15;
                END IF;
                
                -- التأكد من أن الدرجة بين 0 و 100
                IF score < 0 THEN
                    score := 0;
                ELSIF score > 100 THEN
                    score := 100;
                END IF;
                
                NEW.data_quality_score := score;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION calculate_data_quality_score()
            RETURNS TRIGGER AS $$
            DECLARE
                score INTEGER := 0;
            BEGIN
                -- الحقول الإلزامية (10 نقاط لكل حقل)
                IF NEW.military_number IS NOT NULL AND LENGTH(NEW.military_number) = 7 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.national_id IS NOT NULL AND LENGTH(NEW.national_id) = 11 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.full_name IS NOT NULL AND LENGTH(TRIM(NEW.full_name)) > 0 THEN
                    score := score + 10;
                END IF;
                
                IF NEW.birth_date IS NOT NULL THEN
                    score := score + 10;
                END IF;
                
                IF NEW.join_date IS NOT NULL THEN
                    score := score + 10;
                END IF;
                
                -- الحقول الاختيارية (5 نقاط لكل حقل)
                IF NEW.phone_number IS NOT NULL AND TRIM(NEW.phone_number) != '' THEN
                    score := score + 5;
                END IF;
                
                IF NEW.photo IS NOT NULL AND TRIM(NEW.photo) != '' THEN
                    score := score + 10;
                END IF;
                
                IF NEW.fingerprint_hash IS NOT NULL AND TRIM(NEW.fingerprint_hash) != '' THEN
                    score := score + 10;
                END IF;
                
                IF NEW.qualification_id IS NOT NULL THEN
                    score := score + 5;
                END IF;
                
                IF NEW.location_id IS NOT NULL THEN
                    score := score + 5;
                END IF;
                
                -- خصم نقاط للمشاكل (استرجاع is_temporary)
                IF NEW.is_temporary = TRUE THEN
                    score := score - 20;
                END IF;
                
                IF NEW.national_id_status IN ('missing', 'duplicate', 'invalid_length') THEN
                    score := score - 15;
                END IF;
                
                -- التأكد من أن الدرجة بين 0 و 100
                IF score < 0 THEN
                    score := 0;
                ELSIF score > 100 THEN
                    score := 100;
                END IF;
                
                NEW.data_quality_score := score;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
    ]
