# Generated by Django 5.0.2 on 2026-05-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_branch_centraldepartment_districtpolice_geodistrict_and_more"),
        ("personnel", "0019_add_demotion_settlement_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personnelmaster",
            name="personnel_m_directo_9053ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="personnelmaster",
            name="idx_hr_dashboard_filter",
        ),
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="governorate",
        ),
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="location",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="governorate",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="location",
        ),
        migrations.RemoveField(
            model_name="suggestedcorrection",
            name="governorate",
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="central_department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.districtpolice",
                verbose_name="أمن المديرية",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="geo_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="المديرية الجغرافية الفعلية للخدمة والانتشار",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geodistrict",
                verbose_name="الموقع الجغرافي",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="security_admin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="central_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.districtpolice",
                verbose_name="أمن المديرية",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="geo_location",
            field=models.ForeignKey(
                blank=True,
                help_text="المديرية الجغرافية الفعلية للخدمة والانتشار",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stationed_personnel",
                to="core.geodistrict",
                verbose_name="الموقع الجغرافي",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="security_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personnel",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="suggestedcorrection",
            name="security_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggested_corrections",
                to="core.securityadministration",
                verbose_name="إدارة الأمن",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["security_admin", "current_status"],
                name="personnel_m_securit_b41adb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["security_admin", "current_status", "current_rank"],
                name="idx_hr_dashboard_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["central_department"], name="personnel_m_central_0abbf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["branch"], name="personnel_m_branch__d1ef1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["district_police"], name="personnel_m_distric_c798ae_idx"
            ),
        ),
    ]
