# Generated by Django 5.0.2 on 2026-05-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0025_alter_suggestedcorrection_status"),
        ("storage", "0006_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedcorrection",
            name="approval_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_corrections",
                to="storage.document",
                verbose_name="مستند الموافقة (مذكرة الوزارة)",
            ),
        ),
        migrations.AlterField(
            model_name="suggestedcorrection",
            name="supporting_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="storage.document",
                verbose_name="المستند الداعم (الطلب)",
            ),
        ),
    ]
