# Generated by Django 5.0.2 on 2026-05-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0027_suggestedcorrection_linked_correction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="corrected_name",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="corrected_name",
        ),
    ]
