# Generated by Django 5.0.2 on 2026-04-02 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "military_number",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم العسكري يجب أن يكون 7 أرقام بالضبط",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="الرقم العسكري",
                    ),
                ),
                (
                    "old_military_number",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم العسكري القديم يجب أن يكون 7 أرقام",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="الرقم العسكري القديم",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم الوطني يجب أن يكون 11 رقماً",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                ("birth_date", models.DateField(verbose_name="تاريخ الميلاد")),
                ("join_date", models.DateField(verbose_name="تاريخ الالتحاق")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="personnel/photos/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="بصمة (hash)",
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="بيانات كاملة"),
                ),
                (
                    "current_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_personnel",
                        to="core.department",
                        verbose_name="الإدارة الحالية",
                    ),
                ),
                (
                    "current_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_personnel",
                        to="core.rank",
                        verbose_name="الرتبة الحالية",
                    ),
                ),
                (
                    "current_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_personnel",
                        to="core.servicestatus",
                        verbose_name="الحالة الخدمية الحالية",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personnel",
                        to="core.location",
                        verbose_name="الموقع",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel",
                        to="core.qualification",
                        verbose_name="المؤهل الدراسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرد",
                "verbose_name_plural": "الأفراد",
                "db_table": "personnel_master",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["national_id"], name="personnel_m_nationa_57ec78_idx"
                    ),
                    models.Index(
                        fields=["full_name"], name="personnel_m_full_na_61194a_idx"
                    ),
                    models.Index(
                        fields=["current_department", "current_status"],
                        name="personnel_m_current_747d5a_idx",
                    ),
                    models.Index(
                        fields=["current_rank"], name="personnel_m_current_075742_idx"
                    ),
                ],
            },
        ),
    ]
