# Generated by Django 5.0.2 on 2026-04-02 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_personnelmaster_data_quality_score_and_more"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDataImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("row_index", models.IntegerField(verbose_name="رقم الصف")),
                ("raw_data", models.JSONField(verbose_name="البيانات الخام")),
                (
                    "import_batch_id",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="معرف دفعة الاستيراد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processed", "تمت المعالجة"),
                            ("error", "خطأ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
            ],
            options={
                "verbose_name": "بيانات خام مستوردة",
                "verbose_name_plural": "البيانات الخام المستوردة",
                "db_table": "personnel_raw_data_import",
                "ordering": ["import_batch_id", "row_index"],
                "indexes": [
                    models.Index(
                        fields=["import_batch_id"],
                        name="personnel_r_import__ac1362_idx",
                    ),
                    models.Index(
                        fields=["status"], name="personnel_r_status_40b866_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestedCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="اسم الحقل"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="القيمة القديمة"),
                ),
                ("new_value", models.TextField(verbose_name="القيمة الجديدة")),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("name_correction", "تصحيح الاسم"),
                            ("national_id_correction", "تصحيح الرقم الوطني"),
                            ("rank_correction", "تصحيح الرتبة"),
                            ("military_number_correction", "تصحيح الرقم العسكري"),
                        ],
                        max_length=30,
                        verbose_name="نوع التصحيح",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "موافق عليه"),
                            ("rejected", "مرفوض"),
                            ("under_review", "تحت المراجعة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_corrections",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_corrections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلب بواسطة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_corrections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجع بواسطة",
                    ),
                ),
                (
                    "supporting_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="services.document",
                        verbose_name="المستند الداعم",
                    ),
                ),
            ],
            options={
                "verbose_name": "اقتراح تصحيح",
                "verbose_name_plural": "اقتراحات التصحيح",
                "db_table": "personnel_suggested_correction",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMonthlyVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="بصيغة YYYY-MM", max_length=7, verbose_name="الشهر"
                    ),
                ),
                ("variable_value", models.TextField(verbose_name="قيمة المتغير")),
                (
                    "source_column",
                    models.CharField(max_length=100, verbose_name="العمود المصدر"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_variables",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
            ],
            options={
                "verbose_name": "متغير شهري تاريخي",
                "verbose_name_plural": "المتغيرات الشهرية التاريخية",
                "db_table": "personnel_historical_monthly_variables",
                "ordering": ["personnel", "-month"],
                "indexes": [
                    models.Index(
                        fields=["personnel", "month"],
                        name="personnel_h_personn_44d6da_idx",
                    ),
                    models.Index(fields=["month"], name="personnel_h_month_830298_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="historicalmonthlyvariables",
            constraint=models.UniqueConstraint(
                fields=("personnel", "month", "source_column"),
                name="unique_monthly_variable",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcorrection",
            index=models.Index(
                fields=["personnel", "status"], name="personnel_s_personn_79dd65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcorrection",
            index=models.Index(
                fields=["correction_type", "status"],
                name="personnel_s_correct_0cfe15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcorrection",
            index=models.Index(
                fields=["requested_at"], name="personnel_s_request_eed1f6_idx"
            ),
        ),
    ]
