# Generated by Django 5.0.2 on 2026-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_suggestedcorrection_governorate"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. Prevent update of military_number
            CREATE OR REPLACE FUNCTION prevent_military_number_update()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.military_number IS DISTINCT FROM NEW.military_number THEN
                    RAISE EXCEPTION 'Cannot modify military_number. It is a primary key.';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_prevent_military_number_update ON personnel_master;
            CREATE TRIGGER trg_prevent_military_number_update
                BEFORE UPDATE ON personnel_master
                FOR EACH ROW
                EXECUTE FUNCTION prevent_military_number_update();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_prevent_military_number_update ON personnel_master;
            DROP FUNCTION IF EXISTS prevent_military_number_update();
            """
        ),
        migrations.RunSQL(
            sql="""
            -- 2. Calculate data_quality_score and is_complete
            CREATE OR REPLACE FUNCTION calculate_personnel_quality()
            RETURNS TRIGGER AS $$
            DECLARE
                score INTEGER := 0;
            BEGIN
                IF NEW.military_number IS NOT NULL THEN score := score + 20; END IF;
                IF NEW.national_id IS NOT NULL THEN score := score + 20; END IF;
                IF NEW.full_name IS NOT NULL THEN score := score + 20; END IF;
                IF NEW.birth_date IS NOT NULL THEN score := score + 10; END IF;
                IF NEW.join_date IS NOT NULL THEN score := score + 10; END IF;
                IF NEW.current_rank_id IS NOT NULL THEN score := score + 10; END IF;
                IF NEW.current_status_id IS NOT NULL THEN score := score + 10; END IF;
                
                NEW.data_quality_score := score;
                
                NEW.is_complete := (NEW.photo IS NOT NULL AND NEW.photo != '') 
                                   AND (NEW.fingerprint_hash IS NOT NULL AND NEW.fingerprint_hash != '') 
                                   AND (NEW.national_id IS NOT NULL AND NEW.national_id != '');
                                   
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_calculate_personnel_quality ON personnel_master;
            CREATE TRIGGER trg_calculate_personnel_quality
                BEFORE INSERT OR UPDATE ON personnel_master
                FOR EACH ROW
                EXECUTE FUNCTION calculate_personnel_quality();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_calculate_personnel_quality ON personnel_master;
            DROP FUNCTION IF EXISTS calculate_personnel_quality();
            """
        ),
        migrations.RunSQL(
            sql="""
            -- 3. Check constraint for join_date and birth_date
            ALTER TABLE personnel_master 
            ADD CONSTRAINT chk_join_date_after_birth_date 
            CHECK (join_date >= birth_date + interval '18 years');
            """,
            reverse_sql="""
            ALTER TABLE personnel_master DROP CONSTRAINT IF EXISTS chk_join_date_after_birth_date;
            """
        )
    ]
