# Generated by Django 5.0.2 on 2026-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_directorate_node_type_position_allowed_categories_and_more"),
        ("personnel", "0009_add_missing_raw_data_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personnelmaster",
            name="personnel_m_current_747d5a_idx",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="current_department",
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["directorate", "current_status"],
                name="personnel_m_directo_9053ba_idx",
            ),
        ),
    ]
