# Generated by Django 5.0.2 on 2026-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personnel",
            "0010_remove_personnelmaster_personnel_m_current_747d5a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="download_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات التنزيل من الخدمات"
            ),
        ),
    ]
