# Generated by Django 5.0.2 on 2026-05-10 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0011_add_download_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnelmaster",
            name="national_id_duplicate_of",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="national_id_status",
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="الرقم الوطني يجب أن يكون 11 رقماً بالضبط",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="الرقم الوطني",
            ),
        ),
    ]
