# Generated by Django 5.0.2 on 2026-05-11 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_directorate_node_type_position_allowed_categories_and_more"),
        ("personnel", "0012_remove_national_id_status_and_duplicate_of"),
        ("services", "0009_departmentcompliance_unique_compliance_per_org_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RankSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("same_class_promotion", "ترقية ضمن نفس الصنف"),
                            ("personnel_to_officer", "تسوية فرد إلى ضابط"),
                        ],
                        max_length=30,
                        verbose_name="نوع التسوية",
                    ),
                ),
                (
                    "new_military_number",
                    models.CharField(
                        blank=True,
                        help_text="مطلوب فقط عند تسوية فرد إلى ضابط — يجب أن يبدأ بـ 60",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم العسكري الجديد يجب أن يكون 7 أرقام",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="الرقم العسكري الجديد",
                    ),
                ),
                (
                    "decision_number",
                    models.CharField(max_length=50, verbose_name="رقم القرار/المذكرة"),
                ),
                ("decision_date", models.DateField(verbose_name="تاريخ القرار")),
                (
                    "batch_reference",
                    models.CharField(
                        blank=True,
                        help_text="لربط عدة ترقيات صادرة بنفس القرار",
                        max_length=100,
                        null=True,
                        verbose_name="مرجع الدفعة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "تمت الموافقة"),
                            ("rejected", "مرفوض"),
                            ("applied", "تم التطبيق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التطبيق"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "طلب تسوية رتبة",
                "verbose_name_plural": "طلبات تسوية الرتب",
                "db_table": "personnel_rank_settlement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="officer_number",
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="old_military_number",
            field=models.CharField(
                blank=True,
                help_text="يُملأ فقط عند ترقية فرد إلى ضابط أو مجند إلى جندي — يحفظ الرقم القديم للرجوع إليه",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="الرقم العسكري القديم يجب أن يكون 7 أرقام",
                        regex="^\\d{7}$",
                    )
                ],
                verbose_name="الرقم العسكري القديم",
            ),
        ),
        migrations.AddConstraint(
            model_name="personnelmaster",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("old_military_number", models.F("military_number")), _negated=True
                ),
                name="chk_old_mil_num_differs",
            ),
        ),
        migrations.AddConstraint(
            model_name="personnelmaster",
            constraint=models.UniqueConstraint(
                condition=models.Q(("old_military_number__isnull", False)),
                fields=("old_military_number",),
                name="unique_old_military_number_when_set",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_settlements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التطبيق بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="from_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements_from",
                to="core.rank",
                verbose_name="من رتبة",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="personnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_settlements",
                to="personnel.personnelmaster",
                verbose_name="الفرد",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_settlements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="طلب بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="supporting_document",
            field=models.ForeignKey(
                help_text="صورة القرار الرسمي — إلزامي",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rank_settlements",
                to="services.document",
                verbose_name="المرفق الرسمي",
            ),
        ),
        migrations.AddField(
            model_name="ranksettlement",
            name="to_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements_to",
                to="core.rank",
                verbose_name="إلى رتبة",
            ),
        ),
        migrations.AddIndex(
            model_name="ranksettlement",
            index=models.Index(
                fields=["personnel", "status"], name="personnel_r_personn_b433de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranksettlement",
            index=models.Index(fields=["status"], name="personnel_r_status_70a118_idx"),
        ),
        migrations.AddIndex(
            model_name="ranksettlement",
            index=models.Index(
                fields=["batch_reference"], name="personnel_r_batch_r_d69f98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranksettlement",
            index=models.Index(
                fields=["decision_date"], name="personnel_r_decisio_2608b5_idx"
            ),
        ),
    ]
