# Generated by Django 5.0.2 on 2026-05-14 13:44

import systems.personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0013_hardening_military_number_rank_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelmaster",
            name="corrected_name",
            field=models.CharField(
                blank=True,
                help_text="يُملأ عند استيراد البيانات أو طلب التصحيح. يُفرّغ بعد الموافقة الرسمية.",
                max_length=200,
                null=True,
                validators=[
                    systems.personnel.models.validate_arabic_name,
                    systems.personnel.models.validate_name_parts,
                ],
                verbose_name="الاسم المصحح من واقع البطاقة",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="full_name",
            field=models.CharField(
                help_text="الاسم الرباعي أو الخماسي مع اللقب — عربي فقط",
                max_length=200,
                validators=[
                    systems.personnel.models.validate_arabic_name,
                    systems.personnel.models.validate_name_parts,
                ],
                verbose_name="الاسم الكامل",
            ),
        ),
    ]
