# Generated by Django 5.0.2 on 2026-05-16 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0014_add_corrected_name_and_name_validators"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranksettlement",
            name="supporting_document",
            field=models.ForeignKey(
                help_text="صورة القرار الرسمي — إلزامي",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rank_settlements",
                to="storage.document",
                verbose_name="المرفق الرسمي",
            ),
        ),
        migrations.AlterField(
            model_name="suggestedcorrection",
            name="supporting_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="storage.document",
                verbose_name="المستند الداعم",
            ),
        ),
    ]
