# Generated by Django 5.0.2 on 2026-05-16 22:38

import django.core.validators
import django.db.models.deletion
import systems.personnel.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_loginauditlog_login_audit_timestamp_brin_idx"),
        ("personnel", "0015_alter_ranksettlement_supporting_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPersonnelMaster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="تاريخ التحديث"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "military_number",
                    models.CharField(
                        db_index=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم العسكري يجب أن يكون 7 أرقام بالضبط",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="الرقم العسكري",
                    ),
                ),
                (
                    "old_military_number",
                    models.CharField(
                        blank=True,
                        help_text="يُملأ فقط عند ترقية فرد إلى ضابط أو مجند إلى جندي — يحفظ الرقم القديم للرجوع إليه",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم العسكري القديم يجب أن يكون 7 أرقام",
                                regex="^\\d{7}$",
                            )
                        ],
                        verbose_name="الرقم العسكري القديم",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="الرقم الوطني يجب أن يكون 11 رقماً بالضبط",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="الاسم الرباعي أو الخماسي مع اللقب — عربي فقط",
                        max_length=200,
                        validators=[
                            systems.personnel.models.validate_arabic_name,
                            systems.personnel.models.validate_name_parts,
                        ],
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "corrected_name",
                    models.CharField(
                        blank=True,
                        help_text="يُملأ عند استيراد البيانات أو طلب التصحيح. يُفرّغ بعد الموافقة الرسمية.",
                        max_length=200,
                        null=True,
                        validators=[
                            systems.personnel.models.validate_arabic_name,
                            systems.personnel.models.validate_name_parts,
                        ],
                        verbose_name="الاسم المصحح من واقع البطاقة",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الالتحاق"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="بصمة (hash)",
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="بيانات كاملة"),
                ),
                (
                    "is_temporary",
                    models.BooleanField(default=False, verbose_name="رقم عسكري مؤقت"),
                ),
                (
                    "is_data_clean",
                    models.BooleanField(default=False, verbose_name="بيانات نظيفة"),
                ),
                (
                    "data_quality_score",
                    models.IntegerField(default=0, verbose_name="درجة جودة البيانات"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "expense_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("has_expenses", "لديه نفقات"),
                            ("no_expenses", "بدون نفقات"),
                            ("expenses", "نفقات"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="حالة النفقات",
                    ),
                ),
                (
                    "appointment_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات التعيين"
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ صدور القرار"
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التصدور إلينا"
                    ),
                ),
                (
                    "download_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات التنزيل من الخدمات"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical فرد",
                "verbose_name_plural": "historical الأفراد",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["is_deleted"], name="personnel_m_is_dele_b46a22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelmaster",
            index=models.Index(
                fields=["directorate", "current_status", "current_rank"],
                name="idx_hr_dashboard_filter",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.jobcategory",
                verbose_name="الفئة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="current_rank",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.rank",
                verbose_name="الرتبة الحالية",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="current_status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.servicestatus",
                verbose_name="الحالة الخدمية الحالية",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.directorate",
                verbose_name="الإدارة العامة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="division",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.division",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="force_classification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.forcetype",
                verbose_name="تصنيف القوة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.jobtitle",
                verbose_name="نوع العمل",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.location",
                verbose_name="الموقع",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="pending_rank",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.rank",
                verbose_name="الرتبة المعلقة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="position",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.position",
                verbose_name="المنصب",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.qualification",
                verbose_name="المؤهل الدراسي",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.unit",
                verbose_name="الوحدة",
            ),
        ),
    ]
