# Generated by Django 5.0.2 on 2026-05-18 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_variabletype"),
        (
            "personnel",
            "0016_historicalpersonnelmaster_personnelmaster_deleted_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmonthlyvariables",
            options={
                "ordering": ["personnel", "-month"],
                "verbose_name": "متغير شهري",
                "verbose_name_plural": "المتغيرات الشهرية",
            },
        ),
        migrations.RemoveConstraint(
            model_name="historicalmonthlyvariables",
            name="unique_monthly_variable",
        ),
        migrations.RemoveField(
            model_name="historicalpersonnelmaster",
            name="download_notes",
        ),
        migrations.RemoveField(
            model_name="personnelmaster",
            name="download_notes",
        ),
        migrations.AddField(
            model_name="historicalmonthlyvariables",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_variables_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُدخل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonthlyvariables",
            name="source",
            field=models.CharField(
                choices=[
                    ("excel_import", "استيراد من إكسل"),
                    ("manual", "إدخال يدوي"),
                    ("system", "النظام تلقائياً"),
                ],
                default="manual",
                max_length=20,
                verbose_name="المصدر",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonthlyvariables",
            name="variable_type",
            field=models.ForeignKey(
                blank=True,
                help_text="من القاموس الموحد — فارغ فقط للسجلات المستوردة القديمة",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="monthly_records",
                to="core.variabletype",
                verbose_name="نوع المتغير",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmonthlyvariables",
            name="source_column",
            field=models.CharField(
                blank=True,
                default="",
                help_text="اسم العمود الأصلي في الإكسل — يُملأ تلقائياً عند الاستيراد",
                max_length=100,
                verbose_name="العمود المصدر",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmonthlyvariables",
            name="variable_value",
            field=models.TextField(
                help_text="النص الأصلي — يُحفظ دائماً حتى لو تم الربط بالقاموس",
                verbose_name="قيمة المتغير",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonnelmaster",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يتكون من 9 أرقام ويبدأ بالرقم 7",
                        regex="^7\\d{8}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم الهاتف يجب أن يتكون من 9 أرقام ويبدأ بالرقم 7",
                        regex="^7\\d{8}$",
                    )
                ],
                verbose_name="رقم الهاتف",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalmonthlyvariables",
            index=models.Index(
                fields=["variable_type"], name="personnel_h_variabl_dcfe52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicalmonthlyvariables",
            index=models.Index(fields=["source"], name="personnel_h_source_0d5d78_idx"),
        ),
        migrations.AddConstraint(
            model_name="historicalmonthlyvariables",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "excel_import")),
                fields=("personnel", "month", "source_column"),
                name="unique_monthly_variable_import",
            ),
        ),
    ]
