# Generated by Django 5.0.2 on 2026-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0018_remove_is_temporary_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ranksettlement",
            name="settlement_type",
            field=models.CharField(
                choices=[
                    ("same_class_promotion", "ترقية ضمن نفس الصنف"),
                    ("personnel_to_officer", "تسوية فرد إلى ضابط"),
                    ("demotion", "تخفيض رتبة (عقوبة/قرار قضائي)"),
                ],
                max_length=30,
                verbose_name="نوع التسوية",
            ),
        ),
    ]
