# Generated by Django 5.0.2 on 2026-05-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_delete_location_alter_division_options_and_more"),
        (
            "personnel",
            "0020_remove_personnelmaster_personnel_m_directo_9053ba_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdataimport",
            name="linked_personnel",
            field=models.ForeignKey(
                blank=True,
                help_text="يُعبّأ بعد تحويل الصف الخام إلى سجل فرد فعلي",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_imports",
                to="personnel.personnelmaster",
                verbose_name="الفرد المرتبط",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalmonthlyvariables",
            index=models.Index(
                fields=["personnel", "variable_type"], name="idx_mv_person_vartype"
            ),
        ),
        migrations.AddIndex(
            model_name="rawdataimport",
            index=models.Index(
                fields=["linked_personnel"], name="personnel_r_linked__14dc57_idx"
            ),
        ),
    ]
