# Generated by Django 5.0.2 on 2026-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0024_fix_audit_trigger_coalesce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestedcorrection",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("approved", "موافق عليه"),
                    ("rejected", "مرفوض"),
                ],
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
