# Generated by Django 5.0.2 on 2026-05-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0026_suggestedcorrection_approval_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedcorrection",
            name="linked_correction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_corrections",
                to="personnel.suggestedcorrection",
                verbose_name="الطلب المرتبط (تبديل الأرقام)",
            ),
        ),
        migrations.AddField(
            model_name="suggestedcorrection",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="بيانات إضافية"
            ),
        ),
        migrations.AddField(
            model_name="suggestedcorrection",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="ملاحظات داخلية"
            ),
        ),
        migrations.AlterField(
            model_name="suggestedcorrection",
            name="correction_type",
            field=models.CharField(
                choices=[
                    ("name_correction", "تصحيح الاسم"),
                    ("national_id_correction", "تصحيح الرقم الوطني"),
                    ("military_number_correction", "تصحيح الرقم العسكري"),
                ],
                max_length=30,
                verbose_name="نوع التصحيح",
            ),
        ),
    ]
