# Generated by Django 5.0.2 on 2026-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_delete_location_alter_division_options_and_more"),
        ("personnel", "0029_remove_corrected_name_from_trigger"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="personnelmaster",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("branch__isnull", True),
                        ("central_department__isnull", False),
                        ("district_police__isnull", True),
                    ),
                    models.Q(
                        ("branch__isnull", False),
                        ("central_department__isnull", True),
                        ("district_police__isnull", True),
                    ),
                    models.Q(
                        ("branch__isnull", True),
                        ("central_department__isnull", True),
                        ("district_police__isnull", False),
                    ),
                    models.Q(
                        ("branch__isnull", True),
                        ("central_department__isnull", True),
                        ("district_police__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_single_level2_hierarchy",
                violation_error_message="لا يمكن أن يتبع الفرد لأكثر من جهة واحدة في نفس الوقت (إدارة مركزية، فرع، أو أمن مديرية).",
            ),
        ),
    ]
