# Generated by Django 5.0.2 on 2026-06-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_securityadministration_geo_governorate"),
        ("personnel", "0030_personnelmaster_chk_single_level2_hierarchy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonnelmaster",
            name="geo_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="المحافظة الجغرافية الفعلية للخدمة والانتشار",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geogovernorate",
                verbose_name="الموقع الجغرافي",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="geo_location",
            field=models.ForeignKey(
                blank=True,
                help_text="المحافظة الجغرافية الفعلية للخدمة والانتشار",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stationed_personnel",
                to="core.geogovernorate",
                verbose_name="الموقع الجغرافي",
            ),
        ),
    ]
