# Generated by Django 5.0.2 on 2026-06-29 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0031_alter_historicalpersonnelmaster_geo_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonnelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("promotion", "ترقية"),
                            ("transfer", "نقل"),
                            ("status_change", "تغيير حالة"),
                            ("correction", "تصحيح بيانات"),
                            ("document_added", "إضافة مستند"),
                            ("note", "ملاحظة عامة"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="نوع الحدث",
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحدث"),
                ),
                ("description", models.TextField(verbose_name="وصف الحدث")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_personnel_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel_events",
                        to="personnel.personnelmaster",
                        verbose_name="الفرد",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث",
                "verbose_name_plural": "الأحداث",
                "db_table": "personnel_event",
                "ordering": ["-event_date"],
            },
        ),
    ]
