# Generated by Django 5.0.2 on 2026-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0032_personnelevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestedcorrection",
            name="correction_type",
            field=models.CharField(
                choices=[
                    ("name_correction", "تصحيح الاسم"),
                    ("national_id_correction", "تصحيح الرقم الوطني"),
                    ("military_number_correction", "تصحيح الرقم العسكري"),
                    ("data_correction", "تصحيح بيانات أخرى"),
                ],
                max_length=30,
                verbose_name="نوع التصحيح",
            ),
        ),
    ]
