# Generated by Django 5.0.2 on 2026-07-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_securityadministration_geo_governorate'),
        ('personnel', '0033_alter_suggestedcorrection_correction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonnelmaster',
            name='current_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.servicestatus', verbose_name='نوع الحالة الخدمية (التفصيلي)'),
        ),
        migrations.AlterField(
            model_name='personnelmaster',
            name='current_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_personnel', to='core.servicestatus', verbose_name='نوع الحالة الخدمية (التفصيلي)'),
        ),
    ]
