# Generated by Django 5.2.15 on 2026-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0034_alter_historicalpersonnelmaster_current_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedcorrection",
            name="is_printed",
            field=models.BooleanField(default=False, verbose_name="تمت الطباعة"),
        ),
    ]
