# Generated by Django 5.0.2 on 2026-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0035_suggestedcorrection_is_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnelmaster',
            name='temp_status_details',
            field=models.JSONField(blank=True, help_text='بيانات إضافية مثل: اسم المستشفى، نوع القضية، جهة الانتداب، الخ', null=True, verbose_name='تفاصيل الحالة المؤقتة'),
        ),
        migrations.AddField(
            model_name='personnelmaster',
            name='temp_status_details',
            field=models.JSONField(blank=True, help_text='بيانات إضافية مثل: اسم المستشفى، نوع القضية، جهة الانتداب، الخ', null=True, verbose_name='تفاصيل الحالة المؤقتة'),
        ),
    ]
