# Generated by Django 5.0.2 on 2026-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0036_historicalpersonnelmaster_temp_status_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonnelmaster',
            name='audit_movement_details',
            field=models.JSONField(blank=True, help_text='بيانات التنقلات، الانتداب، الغياب، وتصحيح الأسماء', null=True, verbose_name='تفاصيل التدقيق والحركة'),
        ),
        migrations.AddField(
            model_name='historicalpersonnelmaster',
            name='perm_status_details',
            field=models.JSONField(blank=True, help_text='بيانات إضافية مثل: تاريخ الوفاة، نسبة العجز الطبي، رقم القرار، الخ', null=True, verbose_name='تفاصيل الحالة النهائية'),
        ),
        migrations.AddField(
            model_name='personnelmaster',
            name='audit_movement_details',
            field=models.JSONField(blank=True, help_text='بيانات التنقلات، الانتداب، الغياب، وتصحيح الأسماء', null=True, verbose_name='تفاصيل التدقيق والحركة'),
        ),
        migrations.AddField(
            model_name='personnelmaster',
            name='perm_status_details',
            field=models.JSONField(blank=True, help_text='بيانات إضافية مثل: تاريخ الوفاة، نسبة العجز الطبي، رقم القرار، الخ', null=True, verbose_name='تفاصيل الحالة النهائية'),
        ),
    ]
