# Generated by Django 5.0.2 on 2026-07-08 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0037_historicalpersonnelmaster_audit_movement_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.CharField(max_length=7, verbose_name='تاريخ اللقطة (YYYY-MM)')),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرتبة')),
                ('status_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحالة')),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجهة')),
                ('snapshot_data', models.JSONField(help_text='لقطة JSON كاملة لجميع حقول الفرد وقت الأرشفة', verbose_name='بيانات الفرد كاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='personnel.personnelmaster', verbose_name='الفرد')),
            ],
            options={
                'verbose_name': 'لقطة شهرية',
                'verbose_name_plural': 'اللقطات الشهرية',
                'db_table': 'personnel_monthly_snapshot',
                'indexes': [models.Index(fields=['snapshot_date'], name='personnel_m_snapsho_d33e45_idx')],
                'unique_together': {('personnel', 'snapshot_date')},
            },
        ),
    ]
