# Generated by Django 5.2.15 on 2026-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_districtpolice_options_and_more"),
        ("personnel", "0038_monthlysnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonnelmaster",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.districtpolice",
                verbose_name="شرطة المديرية",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="core.districtpolice",
                verbose_name="شرطة المديرية",
            ),
        ),
    ]
