# Generated by Django 5.0.2 on 2026-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0039_alter_historicalpersonnelmaster_district_police_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonnelmaster",
            name="expense_status",
            field=models.CharField(
                blank=True,
                choices=[("has_expenses", "لديه نفقات"), ("no_expenses", "بدون نفقات")],
                max_length=30,
                null=True,
                verbose_name="حالة النفقات",
            ),
        ),
        migrations.AlterField(
            model_name="personnelmaster",
            name="expense_status",
            field=models.CharField(
                blank=True,
                choices=[("has_expenses", "لديه نفقات"), ("no_expenses", "بدون نفقات")],
                max_length=30,
                null=True,
                verbose_name="حالة النفقات",
            ),
        ),
    ]
