# Generated by Django 5.2.15 on 2026-07-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_districtpolice_options_and_more"),
        ("personnel", "0040_alter_historicalpersonnelmaster_expense_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="birth_district",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geodistrict",
                verbose_name="مديرية الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="birth_governorate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geogovernorate",
                verbose_name="محافظة الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="birth_sub_district",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geosubdistrict",
                verbose_name="عزلة الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="birth_village",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geovillage",
                verbose_name="قرية الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="id_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ إصدار الرقم الوطني"
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="id_issue_place",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="جهة إصدار الرقم الوطني",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="residence_district",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geodistrict",
                verbose_name="مديرية الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="residence_governorate",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geogovernorate",
                verbose_name="محافظة الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="residence_sub_district",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geosubdistrict",
                verbose_name="عزلة الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonnelmaster",
            name="residence_village",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.geovillage",
                verbose_name="قرية الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="birth_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_birth_dist",
                to="core.geodistrict",
                verbose_name="مديرية الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="birth_governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_birth_gov",
                to="core.geogovernorate",
                verbose_name="محافظة الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="birth_sub_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_birth_subdist",
                to="core.geosubdistrict",
                verbose_name="عزلة الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="birth_village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_birth_vill",
                to="core.geovillage",
                verbose_name="قرية الميلاد",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="id_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ إصدار الرقم الوطني"
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="id_issue_place",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="جهة إصدار الرقم الوطني",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="residence_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_res_dist",
                to="core.geodistrict",
                verbose_name="مديرية الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="residence_governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_res_gov",
                to="core.geogovernorate",
                verbose_name="محافظة الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="residence_sub_district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_res_subdist",
                to="core.geosubdistrict",
                verbose_name="عزلة الإقامة",
            ),
        ),
        migrations.AddField(
            model_name="personnelmaster",
            name="residence_village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_res_vill",
                to="core.geovillage",
                verbose_name="قرية الإقامة",
            ),
        ),
    ]
