# Generated by Django 5.0.2 on 2026-04-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم الفئة"
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة وظيفية",
                "verbose_name_plural": "الفئات الوظيفية",
                "db_table": "core_job_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الموقع"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="الكود"
                    ),
                ),
            ],
            options={
                "verbose_name": "موقع",
                "verbose_name_plural": "المواقع",
                "db_table": "core_location",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="المؤهل"),
                ),
                ("order", models.IntegerField(unique=True, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "مؤهل دراسي",
                "verbose_name_plural": "المؤهلات الدراسية",
                "db_table": "core_qualification",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="اسم الرتبة"
                    ),
                ),
                ("order", models.IntegerField(unique=True, verbose_name="الترتيب")),
                ("is_officer", models.BooleanField(default=False, verbose_name="ضابط")),
            ],
            options={
                "verbose_name": "رتبة",
                "verbose_name_plural": "الرتب",
                "db_table": "core_rank",
                "ordering": ["order"],
                "indexes": [
                    models.Index(fields=["order"], name="core_rank_order_f3e116_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الحالة"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("active_full", "قوة عاملة فعلية"),
                            ("active_part", "قوة عاملة غير فعلية"),
                            ("inactive_temp", "قوة غير عاملة مؤقتاً"),
                            ("inactive_perm", "قوة غير عاملة نهائياً"),
                        ],
                        max_length=20,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "receives_salary",
                    models.BooleanField(default=True, verbose_name="يستحق راتب"),
                ),
                (
                    "requires_document",
                    models.BooleanField(default=False, verbose_name="يتطلب مستند"),
                ),
                (
                    "is_permanent_deactivation",
                    models.BooleanField(default=False, verbose_name="خروج نهائي"),
                ),
            ],
            options={
                "verbose_name": "حالة خدمية",
                "verbose_name_plural": "الحالات الخدمية",
                "db_table": "core_service_status",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["classification"], name="core_servic_classif_617165_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="اسم الإدارة"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(default=True, verbose_name="داخلية"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.department",
                        verbose_name="الإدارة الأم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إدارة",
                "verbose_name_plural": "الإدارات",
                "db_table": "core_department",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["parent"], name="core_depart_parent__aa9311_idx"
                    ),
                    models.Index(
                        fields=["is_internal"], name="core_depart_is_inte_2a914c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المسمى الوظيفي"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_titles",
                        to="core.jobcategory",
                        verbose_name="الفئة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسمى وظيفي",
                "verbose_name_plural": "المسميات الوظيفية",
                "db_table": "core_job_title",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="core_job_ti_categor_0bd8d4_idx"
                    )
                ],
            },
        ),
    ]
