# Generated by Django 5.0.2 on 2026-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_position_and_enhance_department"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "إدارة",
                "verbose_name_plural": "الإدارات",
            },
        ),
        migrations.RenameIndex(
            model_name="department",
            new_name="core_depart_level_036723_idx",
            old_name="core_depart_level_idx",
        ),
        migrations.RenameIndex(
            model_name="position",
            new_name="core_positi_level_0061d3_idx",
            old_name="core_positi_level_idx",
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="الكود"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_internal",
            field=models.BooleanField(
                default=True,
                help_text="يحدد ما إذا كانت الإدارة داخل الوزارة أم خارجها",
                verbose_name="داخل الوزارة",
            ),
        ),
    ]
