# Generated by Django 5.0.2 on 2026-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_statetransitionrule_and_more"),
        ("personnel", "0008_add_chk_min_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorate",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("directorate", "إدارة"),
                    ("branch", "فرع"),
                    ("district_police", "شرطة مديرية"),
                ],
                default="directorate",
                help_text="إدارة=مركزية، فرع=غير مركزي، شرطة مديرية=ميدانية",
                max_length=20,
                verbose_name="نوع الوحدة",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="allowed_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='مثل: ["إداري", "ميداني"] — فارغ = مسموح لأي فئة',
                verbose_name="الفئات المسموحة",
            ),
        ),
        migrations.AddIndex(
            model_name="directorate",
            index=models.Index(
                fields=["node_type"], name="core_direct_node_ty_0a6b69_idx"
            ),
        ),
    ]
