# Generated by Django 5.0.2 on 2026-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="معرف الجلسة"
            ),
        ),
        migrations.AddField(
            model_name="loginauditlog",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="معرف الجلسة"
            ),
        ),
    ]
