# Generated by Django 5.0.2 on 2026-05-16 22:38

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auditlog_session_key_loginauditlog_session_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loginauditlog",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["timestamp"], name="login_audit_timestamp_brin_idx"
            ),
        ),
    ]
