# Generated by Django 5.0.2 on 2026-05-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_variabletype"),
        ("workflows", "0003_alter_approvalstep_required_role_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions_m2m",
        ),
        migrations.RemoveField(
            model_name="role",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="additional_roles",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="role",
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="granted_by",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="division",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="governorate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="supervised_departments",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="profile",
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
            ],
            database_operations=[]
        )
    ]
