# Generated by Django 5.0.2 on 2026-05-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_rolepermission_permission_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="loginauditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="LoginAuditLog",
        ),
            ],
            database_operations=[]
        )
    ]
