# Generated by Django 5.0.2 on 2026-05-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_loginauditlog_user_delete_auditlog_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="department",
            name="parent",
        ),
    ]
