# Generated by Django 5.0.2 on 2026-05-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_delete_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الفرع")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب المدير"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "فرع",
                "verbose_name_plural": "الفروع",
                "db_table": "branch",
                "ordering": ["security_admin", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CentralDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الإدارة")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب المدير"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "إدارة مركزية",
                "verbose_name_plural": "الإدارات المركزية",
                "db_table": "central_department",
                "ordering": ["security_admin", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DistrictPolice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="يُولّد تلقائياً: أمن مديرية + اسم المديرية",
                        max_length=200,
                        verbose_name="الاسم",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الكود"
                    ),
                ),
                (
                    "head_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منصب المدير"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "أمن مديرية",
                "verbose_name_plural": "أمن المديريات",
                "db_table": "district_police",
                "ordering": ["security_admin", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeoDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزي"
                    ),
                ),
                (
                    "name_ar_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالعربي (بدون تشكيل)",
                    ),
                ),
                (
                    "name_en_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالإنجليزي (موحد)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
            ],
            options={
                "verbose_name": "مديرية جغرافية",
                "verbose_name_plural": "المديريات الجغرافية",
                "db_table": "geo_district",
                "ordering": ["governorate", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="GeoGovernorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="الاسم بالعربي"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزي"
                    ),
                ),
                (
                    "name_ar_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالعربي (بدون تشكيل)",
                    ),
                ),
                (
                    "name_en_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالإنجليزي (موحد)",
                    ),
                ),
                (
                    "phone_numbering_plan",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="مفتاح المحافظة"
                    ),
                ),
                (
                    "capital_name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="العاصمة بالعربي"
                    ),
                ),
                (
                    "capital_name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="العاصمة بالإنجليزي"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
            ],
            options={
                "verbose_name": "محافظة جغرافية",
                "verbose_name_plural": "المحافظات الجغرافية",
                "db_table": "geo_governorate",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="GeoSubDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزي"
                    ),
                ),
                (
                    "name_ar_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالعربي (بدون تشكيل)",
                    ),
                ),
                (
                    "name_en_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالإنجليزي (موحد)",
                    ),
                ),
            ],
            options={
                "verbose_name": "عزلة",
                "verbose_name_plural": "العزل",
                "db_table": "geo_sub_district",
                "ordering": ["district", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="GeoVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربي"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزي"
                    ),
                ),
                (
                    "name_ar_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالعربي (بدون تشكيل)",
                    ),
                ),
                (
                    "name_en_normalized",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الاسم بالإنجليزي (موحد)",
                    ),
                ),
            ],
            options={
                "verbose_name": "قرية",
                "verbose_name_plural": "القرى",
                "db_table": "geo_village",
                "ordering": ["sub_district", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: إدارة أمن المحافظة الأولى",
                        max_length=200,
                        unique=True,
                        verbose_name="الاسم",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="الكود",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "إدارة أمن محافظة",
                "verbose_name_plural": "إدارات أمن المحافظات",
                "db_table": "security_administration",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="directorate",
            name="governorate",
        ),
        migrations.RemoveField(
            model_name="directorate",
            name="head",
        ),
        migrations.RemoveField(
            model_name="division",
            name="directorate",
        ),
        migrations.RemoveField(
            model_name="governorate",
            name="head",
        ),
    ]
