# Generated by Django 5.0.2 on 2026-05-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization",
            "0005_userprofile_branch_userprofile_central_department_and_more",
        ),
        ("core", "0022_branch_centraldepartment_districtpolice_geodistrict_and_more"),
        (
            "personnel",
            "0020_remove_personnelmaster_personnel_m_directo_9053ba_idx_and_more",
        ),
        ("services", "0019_alter_directoratecompliance_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.AlterField(
            model_name="division",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_division",
                to="personnel.personnelmaster",
                verbose_name="رئيس القسم",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_unit",
                to="personnel.personnelmaster",
                verbose_name="رئيس الوحدة",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_branch",
                to="personnel.personnelmaster",
                verbose_name="مدير الفرع",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="core.branch",
                verbose_name="الفرع",
            ),
        ),
        migrations.AddField(
            model_name="centraldepartment",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_central_dept",
                to="personnel.personnelmaster",
                verbose_name="مدير الإدارة",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="central_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="core.centraldepartment",
                verbose_name="الإدارة المركزية",
            ),
        ),
        migrations.AddField(
            model_name="districtpolice",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_district_police",
                to="personnel.personnelmaster",
                verbose_name="مدير أمن المديرية",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="core.districtpolice",
                verbose_name="أمن المديرية",
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("branch__isnull", True),
                        ("central_department__isnull", False),
                        ("district_police__isnull", True),
                    ),
                    models.Q(
                        ("branch__isnull", False),
                        ("central_department__isnull", True),
                        ("district_police__isnull", True),
                    ),
                    models.Q(
                        ("branch__isnull", True),
                        ("central_department__isnull", True),
                        ("district_police__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="division_single_parent",
            ),
        ),
        migrations.AddField(
            model_name="districtpolice",
            name="geo_district",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="police_unit",
                to="core.geodistrict",
                verbose_name="المديرية الجغرافية",
            ),
        ),
        migrations.AddField(
            model_name="geodistrict",
            name="governorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="core.geogovernorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="geosubdistrict",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_districts",
                to="core.geodistrict",
                verbose_name="المديرية",
            ),
        ),
        migrations.AddField(
            model_name="geovillage",
            name="sub_district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="villages",
                to="core.geosubdistrict",
                verbose_name="العزلة",
            ),
        ),
        migrations.AddField(
            model_name="securityadministration",
            name="geo_governorate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_admin",
                to="core.geogovernorate",
                verbose_name="المحافظة الجغرافية",
            ),
        ),
        migrations.AddField(
            model_name="securityadministration",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_security_admin",
                to="personnel.personnelmaster",
                verbose_name="المدير العام",
            ),
        ),
        migrations.AddField(
            model_name="districtpolice",
            name="security_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district_police_units",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="centraldepartment",
            name="security_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="central_departments",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="security_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="core.securityadministration",
                verbose_name="إدارة أمن المحافظة",
            ),
        ),
        migrations.DeleteModel(
            name="Directorate",
        ),
        migrations.DeleteModel(
            name="Governorate",
        ),
        migrations.AddIndex(
            model_name="geodistrict",
            index=models.Index(
                fields=["governorate"], name="geo_distric_governo_a45e58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="geodistrict",
            unique_together={("governorate", "name_ar")},
        ),
        migrations.AddIndex(
            model_name="geosubdistrict",
            index=models.Index(
                fields=["district"], name="geo_sub_dis_distric_0c8db3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geovillage",
            index=models.Index(
                fields=["sub_district"], name="geo_village_sub_dis_10950d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centraldepartment",
            unique_together={("security_admin", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("security_admin", "code")},
        ),
    ]
