# Generated by Django 5.2.15 on 2026-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_securityadministration_geo_governorate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityadministration",
            name="geo_governorate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_admin",
                to="core.geogovernorate",
                verbose_name="المحافظة الجغرافية",
            ),
        ),
    ]
