# Generated by Django 5.2.15 on 2026-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_securityadministration_geo_governorate"),
        ("personnel", "0038_monthlysnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="districtpolice",
            options={
                "ordering": ["security_admin", "order", "name"],
                "verbose_name": "شرطة مديرية",
                "verbose_name_plural": "شرطات المديريات",
            },
        ),
        migrations.AlterModelOptions(
            name="jobcategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "فئة وظيفية",
                "verbose_name_plural": "الفئات الوظيفية",
            },
        ),
        migrations.AddField(
            model_name="jobcategory",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="ترتيب الفرز"),
        ),
        migrations.AlterField(
            model_name="districtpolice",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_district_police",
                to="personnel.personnelmaster",
                verbose_name="مدير شرطة المديرية",
            ),
        ),
        migrations.AlterField(
            model_name="districtpolice",
            name="name",
            field=models.CharField(
                help_text="يُولّد تلقائياً: شرطة مديرية + اسم المديرية",
                max_length=200,
                verbose_name="الاسم",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="district_police",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="core.districtpolice",
                verbose_name="شرطة المديرية",
            ),
        ),
    ]
