# Generated by Django 5.0.2 on 2026-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_districtpolice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("retirement", "إعدادات التقاعد"),
                            ("promotions", "إعدادات الترقيات"),
                            ("services", "إعدادات الخدمات"),
                            ("holidays", "إعدادات الإجازات"),
                            ("system", "إعدادات عامة للنظام"),
                        ],
                        max_length=50,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح البرمجي"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="العنوان (للعرض)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف المساعد"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("int", "رقم صحيح"),
                            ("float", "رقم عشري"),
                            ("bool", "منطقي (صح/خطأ)"),
                            ("str", "نص"),
                            ("json", "بيانات معقدة (JSON)"),
                        ],
                        default="str",
                        max_length=20,
                        verbose_name="نوع القيمة",
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "db_table": "core_system_setting",
                "ordering": ["category", "title"],
            },
        ),
    ]
