# Generated by Django 5.0.2 on 2026-04-03 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_department_options_and_more"),
        (
            "services",
            "0003_rename_services_de_service_idx_services_de_service_fd876d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                ("slug", models.SlugField(unique=True, verbose_name="الرمز")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("personnel_summary", "ملخص الأفراد"),
                            ("department_strength", "قوة الإدارات"),
                            ("monthly_changes", "التغييرات الشهرية"),
                            ("rejections_report", "تقرير المرفوضات"),
                        ],
                        max_length=50,
                        verbose_name="نوع القالب",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="المعايير الافتراضية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قالب تقرير",
                "verbose_name_plural": "قوالب التقارير",
                "db_table": "services_report_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="نقطة نهاية HTTPS لإرسال الإشعارات",
                        verbose_name="عنوان URL",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="مفتاح HMAC للتوقيع",
                        max_length=128,
                        verbose_name="المفتاح السري",
                    ),
                ),
                (
                    "events",
                    models.JSONField(default=list, verbose_name="الأحداث المفعّلة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
                (
                    "last_response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="آخر كود استجابة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="فارغ = جميع الإدارات",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_configs",
                        to="core.department",
                        verbose_name="الإدارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد Webhook",
                "verbose_name_plural": "إعدادات Webhook",
                "db_table": "services_webhook_config",
            },
        ),
    ]
