# Generated by Django 5.0.2 on 2026-05-12 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0013_hardening_military_number_rank_settlement"),
        ("services", "0010_add_document_type_and_personnel_to_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="context_id",
            field=models.CharField(
                blank=True,
                help_text="المعرف الفريد للكيان المرتبط",
                max_length=50,
                null=True,
                verbose_name="معرف السياق",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="context_type",
            field=models.CharField(
                blank=True,
                help_text="نوع الكيان المرتبط — مثل: SuggestedCorrection, RankSettlement, ServiceEventLog",
                max_length=50,
                null=True,
                verbose_name="نوع السياق",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="related_field",
            field=models.CharField(
                blank=True,
                help_text="اسم الحقل الذي يخص هذا المرفق — مثل: national_id, military_number, current_rank, current_status, full_name",
                max_length=50,
                null=True,
                verbose_name="الحقل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_method",
            field=models.CharField(
                choices=[
                    ("upload", "رفع من الكمبيوتر"),
                    ("scanner", "ماسح ضوئي"),
                    ("camera", "كاميرا / هاتف"),
                ],
                default="upload",
                max_length=10,
                verbose_name="طريقة الرفع",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("national_id_front", "بطاقة وطنية - أمامي"),
                    ("national_id_back", "بطاقة وطنية - خلفي"),
                    ("national_id_scan", "بطاقة وطنية - ماسح ضوئي"),
                    ("military_id_front", "بطاقة عسكرية - أمامي"),
                    ("military_id_back", "بطاقة عسكرية - خلفي"),
                    ("rank_decision", "قرار ترقية"),
                    ("settlement_decision", "قرار تسوية فرد→ضابط"),
                    ("transfer_order", "أمر نقل"),
                    ("name_correction_order", "قرار تصحيح اسم"),
                    ("status_change_order", "قرار تغيير حالة خدمية"),
                    ("leave_request", "طلب إجازة"),
                    ("medical_report", "تقرير طبي"),
                    ("sick_leave", "إجازة مرضية"),
                    ("memo", "مذكرة"),
                    ("letter", "خطاب رسمي"),
                    ("certificate", "شهادة"),
                    ("personal_photo", "صورة شخصية"),
                    ("other", "أخرى"),
                ],
                default="other",
                help_text="تصنيف المرفق — بطاقة وطنية، قرار ترقية، إلخ",
                max_length=30,
                verbose_name="نوع المرفق",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="services_do_documen_993f49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["related_field"], name="services_do_related_a9221c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["context_type", "context_id"],
                name="services_do_context_f4a698_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["personnel", "document_type"],
                name="services_do_personn_6d70e7_idx",
            ),
        ),
    ]
