# Generated by Django 5.0.2 on 2026-05-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0013_hardening_military_number_rank_settlement"),
        ("services", "0011_add_document_context_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="personnel.personnelmaster",
                verbose_name="الفرد",
            ),
        ),
    ]
