# Generated by Django 5.0.2 on 2026-05-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_remove_auditlog_notification_to_core"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="personnel",
        ),
        migrations.RemoveField(
            model_name="document",
            name="temp_owner",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
    ]
